### ISSUE TITLE
Mi Band 2: service / characteristic ID for button press

### ISSUE THREAD

**Issue by ragcsalo** [Freeyourgadget/Gadgetbridge#1044]
This is not an issue, I just need some help. I write a BT LE communication app for the Mi Band 2, which would recognise button presses. The only thing I can't find is the service / characteristic ID for button press.
Could you help me with that, please? Many thanks in advance!!! :-)

**Comment by danielegobbetti** [comment]
Closing since:
- issue template wasn't used
- search functionality was clearly not used (I just tried and found the result among the first five entries within code)
- you opened the same issue [in other repositories as well](https://github.com/inFullMobile/inFullBand/issues/1)

No hard feeling, if you find something in our code that you cannot understand feel free to ask for clarification, but don't expect people to do searches for you.
