### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by ahsim** [Freeyourgadget/Gadgetbridge#1071]
I can't connect to my Amazfit Bip on 25.1 and 26.0 version.
In 25.0 everything is ok
Some other users have same problem. I dont know reason. Maybe you can fit this.
Android 6 MIUI 8 Xiaomi Redmi 4 prime

**Comment by danielegobbetti** [comment]
Please provide logs and the firmware version of your gadget.

Next time don't forget to use the issue template

**Comment by chemary** [comment]
#### Your issue is:
I connected on the past with version (113) but with the 0.26.0 stays "connecting" forever.
I tried to reinstall Gadgetbridge, reinstall Mi Fit, switching on/off "Enable Bluetooth pairing", deleting the device and adding again (It finds the device fine)

#### Your wearable device is:
Amazfit Bip V0.1.1.14

#### Your android version is:
Samsung A3 2015 Android 6.0.1

#### Your Gadgetbridge version is:
0.26.0

Log:
[gadgetbridge.log](https://github.com/Freeyourgadget/Gadgetbridge/files/1921435/gadgetbridge.log)

**Comment by cpfeiffer** [comment]
Please use 0.26.1, which fixes this issue.

**Comment by ahsim** [comment]
why you close this issue? I still prepare logs for you

**Comment by IzzySoft** [comment]
@ahsim because the issue is solved with the new release, as Carsten stated with his comment? Or does it still persist after you've updated to v0.26.1?

**Comment by ahsim** [comment]
No, in v0.26.1 everything is ok with this

**Comment by IzzySoft** [comment]
And that's why Carsten closed this issue :wink:
