### ISSUE TITLE
Mi Band: Reset/Wipe option

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#109]
As a person that is always concerned about privacy, I thought it might be a good idea to have a reset option that wipes all data on the Mi Band and effectively restores everything to factory defaults.
AFAIK, the protocol allows such a feature.

**Comment by cpfeiffer** [comment]
Yes, that's certainly doable and should be pretty easy, too.

**Comment by gtank** [comment]
The protocol makes this look straighforward; is there an overview of the Gadgetbridge architecture somewhere?

**Comment by cpfeiffer** [comment]
Not yet, but I have documentation high on my todo list. For a start, have a look at the class MiBandSupport and all those onXYZ() methods. They are called from the DeviceCommunicationService which is triggered by ui interaction via the DeviceService facade.

You can easily extend the DebugActivity to try out your feature quickly.

**Comment by cpfeiffer** [comment]
And have a look at ActivityDatabaseHandler of you also want to clear the database. The user configuration (name, age, weight, etc. is stored in Android SharedPreferences.

And finally, there's the logfile in case logging is enabled.

**Comment by gtank** [comment]
@cpfeiffer My first pass at this: https://github.com/gtank/Gadgetbridge/commit/e1acf35bd79a8d86cfe9291edac9df8a3bcfc361

It seems to make the characteristic write, but it certainly doesn't do anything that looks like a factory reset. Any obvious mistakes?

**Comment by danielegobbetti** [comment]
@gtank what you did looks good to me. Rebooting after sending the message may be worth a try: fw upload seemed to have no effect until I rebooted the band manually, therefore we are now rebooting the band as soon as we receive the notification that the fw upload was successful. See [this](https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/miband/operations/UpdateFirmwareOperation.java) subclass and do not hesitate to ask for clarifications if needed (but I am sure you don't need any :-) )

Try to see if you get in your logcat some data from the notifications characteristic outputted by:
  LOG.warn("DATA: " + String.format("0x%2x", b)); //row 667 of MiBandSupport.java in current master

That could be the means used by the band to confirm that the factory reset was performed, but I have no idea which values you could be getting.

Another possibility is trying to use the "Remote Disconnect" functionality as described [here](http://allmydroids.blogspot.it/2014/12/xiaomi-mi-band-ble-protocol-reverse.html), i.e. writing 1 to the TEST characteristic (FF0D) instead of the message you are using, and see what happens.

**Comment by cpfeiffer** [comment]
Excellent work! Looks perfect to me. Like Daniele said, the log should show that the command is sent and possibly a reply confirming the successful write.

How the band reacts, I contrarily don't know. After sending the command, we should probably disconnect and possibly even unpair the device to avoid sending the user info back to the band.

To confirm the successful reset, I would try this at a time when there is a certain amount  of unsynchronized activity data on the band. 

After the reset, connect again and synchronize. The activity data should be lost.

**Comment by danielegobbetti** [comment]
@cpfeiffer about the unpairing that may (*may*) not be necessary, at least for testing.
If the band really cleared its data then at the next connection it should ask the user to confirm the connection by blinking and vibrating.

**Comment by gtank** [comment]
Well, the band doesn't react in any way that I can tell- in fact, the write doesn't seem to happen/be acknowledged (depending on how to interpret the logs) until a subsequent command has been issued. I'll see how it interacts with remote disconnect, though.

**Comment by cpfeiffer** [comment]
@gtank At the moment I can't try this out myself -- way too little time, but if you post a logfile, I can have a look at it and explain.

**Comment by cpfeiffer** [comment]
Any progress on this? Do you need any help?

**Comment by gtank** [comment]
Sorry for dropping off on this, I just haven't had time to dig into why it might not be responding.

**Comment by cpfeiffer** [comment]
No problem. Just come back, when you have more time/interest again. Until then, I'll close it as "won't fix" because there are so many other things to do.

**Comment by mentulatore** [comment]
First of all, thank you for this awesome project!
Sorry to necropost here but do you think that this issue could be reopened?
It seems to be already possible to reset the Mi Band models through Gadgetbridge but only with some kind of patching: could you please document the process? (even stating it's unsupported)

@ashimokawa:
> Ok, I know how to factory reset the band (needs patching of gadgetbridge)

Cheers,
mentulatore

**Comment by mentulatore** [comment]
Could you please answer my question?

Cheers,
mentulatore

**Comment by ashimokawa** [comment]
At least for the mi band 2 and 3 I could implement it. Mi band 1 no idea.

**Comment by mentulatore** [comment]
> At least for the mi band 2 and 3 I could implement it. Mi band 1 no idea.

Well, I think that would be a great addition to Gadgetbridge! (I've only got a Mi Band 3).

Thank you very much,
mentulatore

**Comment by ashimokawa** [comment]
Yep. Will probably be in the next release
