### ISSUE TITLE
ZeTime support request

### ISSUE THREAD

**Issue by SMaiz** [Freeyourgadget/Gadgetbridge#1099]
[ZeTime](https://www.mykronoz.com/eu/en/zetime.html) is an hybrid smartwatch (with both screen and hands). Its [official app](https://play.google.com/store/apps/details?id=com.mykronoz.zetime) is not open source, and there is no documentation on the protocol used.
I have started reverse-engineering the protocol (see [this](https://github.com/Freeyourgadget/Gadgetbridge/files/2009617/zetime_protocol_clean.txt) file), but it's far from finished. I will try to complete this protocol description over time, but I am not a BLE expert... Also, while I have already developped a couple apps, I am not an Android developper.

This issue is just here in order to find other interessed people, who have a ZeTime, some time and Android developpment knowledge.

**Comment by Lightwars** [comment]
Hello SMaiz,

it is nice to read about someone, who is interested in getting support for the ZeTime. 
And really awesome you start writing down, how the protocol is structured.

Awhile ago I started adding support for ZeTime in gadgetbridge. I had setuped the basic, so the app connects to the watch. But haven't done more, because the offical app starts handle notifications I was missing and had to recompile in, back in the days.

If I got time I could grab my modifications and start to do some basic stuff with your written down protocol, maybe we got something to work. I pushed some files to my github, find the repo [here](https://github.com/Lightwars/gadgetbridge)

Regards,
Sebastian

**Comment by Lightwars** [comment]
Ok, now first test, after figuring out how some things are done, was successful. Asking the ZeTime about available infos, it responded correctly.
Next is to build as much basic function as possible. And looking at the device finding, pairing and bonding.

**Comment by SMaiz** [comment]
Hi !
I've tested you're code, and the connection is working. That's a good starting point !
I tried to understand the code a little bit, but I don't think I will be able to implement low-level functions, BLE is still a complex thing for me...
I am currently working on the missing parts of the protocol, I'll keep you updated

**Comment by Lightwars** [comment]
Now there are some basic function working and I opened a thread on xda-developers.com to attract some tester and some people who are interested to work on this also.
[Find it here](https://forum.xda-developers.com/android/apps-games/testing-gadgetbridge-zetime-support-t3813241)

There you will find a apk ready to install it.

**Comment by ashimokawa** [comment]
I would prefer pull requests and have this mainlined, for me it is perfectly fine if it is in early stages.

**Comment by ashimokawa** [comment]
Closing this because it was merged in master #1148 and will be released with 0.28.0
