### ISSUE TITLE
Mi Band 2 - Automatic sync of activity data [Feature Request]

### ISSUE THREAD

**Issue by kaefert** [Freeyourgadget/Gadgetbridge#1116]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I wished there was the option for an automatic sync of activity data from the wearable into the Gadgetbridge Database on the phone.

Sometimes I don't open the Gadgetbridge app for a few days and I would like to not have to press the Sync button manually (or wipe down on the statistics page) to get my activity data from my Mi Band 2 into the Gadgetbridge Database.

Otherwise I'm quite happy with Gadgetbridge and particularly with the notification features and configuration options! 

#### Your wearable device is:
Mi Band 2
FW: 1.0.1.53
HW: V0.1.3.3

#### Your android version is:
LG G6, Android 7

#### Your Gadgetbridge version is:
0.26.5

**Comment by danielegobbetti** [comment]
The main problem with this, is that any notification that arrives while the wearable is busy will not be forwarded to it, which is not what the user is expecting.

**Comment by kaefert** [comment]
Well, maybe you could make the time for auto sync configurable so that it's possible to make it happen during the night when most people have silenced their notifications anyway.

**Comment by danielegobbetti** [comment]
I was thinking of starting a fetch when the screen gets turned on, but apparently we can't get that event :(

**Comment by ritualz** [comment]
I'm been missing this feature too, and kinda implemented it. It will basically fetch the activity on screen-unlock.

There is a few additional things I believe is needed:
1. time-interval between fetches (so that it not fetch the data every time the device is unlocked), where can i find this info?
2. check if the device are connected and busy. The DeviceManager inside the new  BroadcastReceiver, report false to these, even when the device is connected.


https://github.com/ritualz/Gadgetbridge/commit/da82c0ce056af863e35030feb9cd26bb82642b8d

**Comment by danielegobbetti** [comment]
@ritualz can you make a pull request with your changes?

**Comment by LuccoJ** [comment]
@danielegobbetti soon enough, if Google have their way, the only event you'll be able to get is going to be a GCM-no-i-mean-Firebase notification.

**Comment by LuccoJ** [comment]
@danielegobbetti 

>The main problem with this, is that any notification that arrives while the wearable is busy will not be forwarded to it, which is not what the user is expecting.

Well, this reminds me of another thing that isn't a feature request because I thought it's something I should just go and write, but then never did, for... a pretty long time I've been thinking of it.

The Bluetooth range of Gadgetbridge-supported devices tend to be pretty low (or at least in line with standard nominal Bluetooth ranges, i.e. pretty low), so it's very easy to miss notifications *anyway* unless you're always glued to your phone. A neat feature would be if Gadgetbridge remembered which notifications it has managed to push to a connected device, and which it hasn't, and at the time a device finally becomes connected again, any unpushed notifications that haven't gone away on their own in the meanwhile (or removed from the phone by the user) would be pushed to the device. Maybe with a time limit so you don't get flooded with too many notifications in case of long connection "blackouts" (or, in those cases, Gadgetbridge could send a *single* notification that just says "Pending notifications after disconnection; check phone").

Still think it's something I should go and try adding if I want it, but since I've not been doing it, I may as well write it down.
