### ISSUE TITLE
Pebble: Set application icons for generic notifications

### ISSUE THREAD

**Issue by roidelapluie** [Freeyourgadget/Gadgetbridge#116]
It would be nice if we could set custom notifications for different apps:

Twidere notifications could get the twitter logo and be in blue for example.

**Comment by ashimokawa** [comment]
I totally agree.
For that we would have to change the API so that we can pass either the full android package name for a generic notification source to the pebble specific code and then decide which icon to use for which specific source, or pre-group them in different categories (chat, social network, email) in generic code before.

**Comment by roidelapluie** [comment]
@ashimokawa Proof of concept available in #118.
