### ISSUE TITLE
New device: ROIDMI

### ISSUE THREAD

**Issue by joserebelo** [Freeyourgadget/Gadgetbridge#1174]
[ROIDMI](http://www.roidmi.com/lanchong-index-en) car chargers are basically FM transmitters with bluetooth. I've been poking around and got most of the protocol working for the first ROIDMI (just some basic bluetooth classic) only missing the activity to control it. I will have the ROIDMI 3s working soon, as well (which might actually include firmware update support, from what I have heard, so the protocol might differ a lot).

The official app, in addition to having way too many unnecessary permissions, even forced the usage of a Xiaomi or Facebook account some time in the past.

These aren't really wearable devices, and would mostly only benefit from Gadgetbridge's bluetooth stack. Functions include changing the LED color / FM frequency, and maybe receive information about the car's battery voltage / execute some action when connected. Even the find device button (which isn't removable at the moment) would do nothing.

What's your stance on the inclusion of this kind of devices in Gadgetbridge?

**Comment by cpfeiffer** [comment]
I'd be fine with that. Looking forward to seeing more diversity among the supported gadgets!

**Comment by joserebelo** [comment]
@cpfeiffer @danielegobbetti 
Small question ()

**Comment by joserebelo** [comment]
The implementation is almost done (https://github.com/joserebelo/Gadgetbridge/commit/700092262a3d9638fe7108270653cbd329ec56f9), just needs some fixes and a cleanup/rebase.

I have, however, run into a bit of a problem when structuring the device specific actions. The led color / fm frequency are not really preferences, I have added them as actions as per @danielegobbetti suggestion in https://github.com/Freeyourgadget/Gadgetbridge/issues/1165#issuecomment-408416022. They should be obtained and changed in real-time on the device, with the current value shown under/on the action icon.

It seems to me that the simplest course of action is to add the led color and fm frequency properties to GBDevice (https://github.com/joserebelo/Gadgetbridge/commit/700092262a3d9638fe7108270653cbd329ec56f9#diff-d5e00ac52c9ce247c3038db8572bff37), as well as the voltage, which can be reported even if there is no battery. These seem to be a bit too specific, and I'm not sure if I'm not bloating the GBDevice class, as well as the Coordinators.

Any thoughts on how to best proceed?

**Comment by neFAST** [comment]
Nice addition! I tested this on m Roidmi 2s and can confirm it works.
Have you found the command codes for other functions? Like enabling/disabling the mic?
Thanks a lot!

**Comment by neFAST** [comment]
@joserebelo Maybe I missed something (I just discovered FreeYourGadget) Are there more options that Fm frequency and led color?

**Comment by joserebelo** [comment]
@neFAST there's also the car battery voltage readout for the 3s (don't know if the 2s supports it). I got the protocol for the denoise option, it's in the code, but haven't implemented it in the GUI yet (personally I didn't notice any difference), but I could add it.

Are there any other missing options?

**Comment by joserebelo** [comment]
Not possible, the Roidmi 3 does not have a microphone.

**Comment by neFAST** [comment]
Hi @joserebelo I still need to look at other options for the Roidmi 2s, I've not been able to retrieve logs yet.
On the other hand I was given a cheap bluetooth "cube" that monitors temp/pressure/humidy and the official app being crap I wanted to integrate it into Gadgetbridge.
Someone already wrote some python code to work with it but I'm not sure how he can read from this address: https://github.com/jeedom/plugin-blea/blob/d71c0e669393d1a98dd1aeffeb02ca154a218cca/resources/blead/devices/hector.py#L31
What advices would you give me in order to write a simple "plugin" for that device?

(BTW I've never coded anything for android so I'm total newbie)

**Comment by joserebelo** [comment]
Hello @neFAST 

The hard part is usually getting the protocol, and that python code already did that. That device uses BLE characteristics and not RFCOMM like the ROIDMI, so the implementation will be slightly different. I'm not that comfortable with those, but it should not be that hard. There's a new device tutorial on the wiki that should help you setup the base for the device in the project, althought I'm not sure how up-to-date it is.

You will need some background on Java at least. I have been meaing to propose some changes to GadgetBridge in order to make adding new devices a bit easier, I might try to post them this weekend.

In either case, maybe create an issue for the new device, and don't hesitate to ask if you need help :)

**Comment by neFAST** [comment]
@joserebelo Thanks for your answer. I already read and followed the wiki. I'm at a point I'm trying to readCharacteristics,however the BTLE class expect quite long UUID like this "000033f3-0000-1000-8000-00805f9b34fb" when the python code I found seems to read from short adresses/registers 0x1d

**Comment by neFAST** [comment]
@joserebelo I will create an issue, thanks again. I tried the base_uuid already without success. Happy new year!

**Comment by Oleg69** [comment]
Dear community,
I own a 3s and only use it for charging purpose, because all FM frequency's are heavily occupied, I haven't found any stable FM frequency that work constantly with 3s for a area of 10km without beginning to swoosh. Anyway, I will use the 3s for permanent car battery monitoring since my second phone is permanent "charging" on 3s ( always-on car assistant) to prevent car battery death. My idea is to push the battery level to tasker which send me a notification if it's low. Meanwhile car temp, humidity, car traking and more are pushing well if critical value or requested, but I will extend my "system" for pushing car battery level too. Is it theoretical possible with gadgetbridge as soon as it support 3s? Or have I to look for another way/solution for it?
Thanks

**Comment by joserebelo** [comment]
@Oleg69 the Roidmi 3s has been supported since #1289, and Gadgetbridge already receives the battery voltage, just not in real time (yet) :)

It should be possible to support your scenario, especially after #1435 is merged, although I haven't looked into the merge request in too much detail.

**Comment by Oleg69** [comment]
@joserebelo Thank you, I will give it a try this weekend
