### ISSUE TITLE
Pebble: Support reporting connection state to PebbleKit Apps

### ISSUE THREAD

**Issue by ashimokawa** [Freeyourgadget/Gadgetbridge#130]
Some PebbleKit Apps such as "Canvas for Pebble" and "Push to Pebble" (any FOSS Apps???) request connection state though a content provider for which the official Pebble App is the authority.

To make them work, we must become the content authority for com.getpebble.android.state or com.getpebble.android.basalt.state which unfortunately would make Gadgetbridge mutual exclusive with the official Pebble App. While I personally don't care, it might scare off new users wanting to try both.

An alternative solution suggested by @danielegobbetti would be to build a new optional App which contains only the content authority and would communicate with Gadgetbridge. That App would also be mutual exclusive with the official App. That way users could choose to have Gadgetbridge with limited PebbleKit support (like it is now), or full support when removing the official App in favour of the optional to be created addon App.

**Comment by glitchphan** [comment]
I don't normally add pics to my contacts, but I added a test one with a random picture. I see the Pebble Dialer incoming call screen with name and phone number in small font, but no pics other than the button icons. I like Pebble Dialer because it gives the option for different button actions. My middle button answers and both top and bottom will mute with short press and decline with long press. There's supposed to be a reject with SMS option, but that doesn't seem to work either. And of course when I set Phone Calls to always, incoming calls were no different from before, just showing the phone icon with the name and accept/decline buttons.

**Comment by ashimokawa** [comment]
@glitchphan 
You mean without Pebble Dialer you have the option to accept a call?
Didn't know that, I only have the option to decline on FW 2.9.1

**Comment by glitchphan** [comment]
Oops, you are right, only decline button.

**Comment by danielegobbetti** [comment]
The app mentioned in #208 uses this method, and won't deliver data to the pebble through gadgetbrige.

**Comment by kas70** [comment]
Thanks @danielegobbetti for investigating. Is this likely to be solved in the near future? To be honest, i bought my pebble just for getting runnerup data onto my wrist;)
Anyway thanks for your work!

**Comment by ashimokawa** [comment]
Yes but only if you promise to never file an issue that complains about Gadgetbridge being unable to install while the official app is installed.

**Comment by kas70** [comment]
Agreed.

**Comment by ashimokawa** [comment]
I implemented a fake content provider which always reports that a pebble is connected (even if is not)
This makes runnerup work.
Its a dirty hack though.

**Comment by kas70** [comment]
Great, thanks!:)

**Comment by danielegobbetti** [comment]
@kas70 can you perhaps help with #188 ?

**Comment by kas70** [comment]
I don't think so as i have a pebble classic, which doesn't support pebble health.

**Comment by danielegobbetti** [comment]
thanks nevertheless :)

**Comment by ashimokawa** [comment]
I am closing this because it is implemented and will be in 0.7.3
