### ISSUE TITLE
MiBand3: Display temp in F

### ISSUE THREAD

**Issue by ee-gary** [Freeyourgadget/Gadgetbridge#1315]
MiBand3 + Gadgetbridge + Weather notification installed and configured per:
https://github.com/Freeyourgadget/Gadgetbridge/wiki/Amazfit-Bip-Weather

MiBand3 correctly shows weather, but temperatures are in 'C'. Requesting configurable option to allow temperature to be shown in 'F'. This can be done in the mifit app: "in mifit , click on your device, weather settings, temperature units"
https://www.reddit.com/r/miband/comments/8zn330/switch_weather_to_fahrenheit/

Mi Band 3 [FW: 1.6.0.16, HW: V0.18.4.1]
Gadgetbridge  [0.30.0]
Weather notification [0.3.10]

**Comment by cpfeiffer** [comment]
I don't know how MiFit does it. Either the Mi Band 3 does the conversion itself, and one just has to configure the band which unit to use, or one has to send the some extra bytes to tell the band that a given temperature is in Fahrenheit instead of Celsius.

If you have Mi Fit, you can capture an hcidump while changing the setting and see what data is sent to the band.

**Comment by ashimokawa** [comment]
I assume Mi Fit does the conversion - the devices never display XX°C , just XX°. We should do that also.
