### ISSUE TITLE
how to donate?

### ISSUE THREAD

**Issue by tristan-k** [Freeyourgadget/Gadgetbridge#14]
I really appreciate your effort in developing Gadgetbridge. Keep up the great work! Is there a way I can donate?

**Comment by ashimokawa** [comment]
Thank you for your encouraging words.
Right now I have not set up any donation system. But I will look at the options. Any suggestions?

**Comment by ddagunts** [comment]
Awesome app, very useful to me, I'd donate a few bucks..

**Comment by ddagunts** [comment]
got PayPal?

**Comment by chrisvella** [comment]
@ashimokawa depends how you want to do it. You could implement payments for contributions i.e. https://tip4commit.com and https://www.bountysource.com/

Or setup a paypal address where you can receive donations.

Another open source app called "conversations" has the app available for free in fdroid, but charges on google play. When the app has more maturity you could try that.

**Comment by krayon** [comment]
Accepting payment via bitcoin is trivial and good for those who don't trust/like/use PayPal et al.

**Comment by ashimokawa** [comment]
@krayon 
Well, everything seems trivial after you understood it ;)
I created a wallet but I still don't get how I can accept bitcoins when the receiving address change with every transaction.

**Comment by shtrom** [comment]
Flattr?

**Comment by vext01** [comment]
I would also like to donate.

I recently bought a miband without doing my homework. Then I found: https://openeffect.ca/reports/Every_Step_You_Fake.pdf

So thankyou, thankyou, thankyou for developing this software, now shuddup and take our money :)

Can we not send via paypal?

**Comment by Zetaphor** [comment]
In light of the [recent news from Pebble](https://blog.getpebble.com/2016/12/07/fitbit/), I feel that you're going to get a sudden influx of interest in this project. I've posted the F-Droid page [over at reddit](https://www.reddit.com/r/pebble/comments/5h0twp/in_light_of_recent_news_gadgetbridge_open_source/), and people are already talking/asking about the ability to donate.

If like many people you find supplemental income encouraging, I and many other dedicated Pebble users would like to assist financially to see that development continues well into the future.

**Comment by CometUK** [comment]
Can I echo Zetaphor's comment? My Pebble isn't going in the bin any time soon.  I'd happily show my support for further work on this software to keep it usable for as long as possible. 

Thank you for all your  work to date.

**Comment by anantshri** [comment]
I am happy to share hosting cost or a fix monthly / yearly donation if this project can keep my pebble up and running. 

Thanks for all the work done so far and looking forward to helping out as much as possible.

**Comment by gianlucapir** [comment]
Hello, have you activated something for the donation? You did a great job and I would like to donate something for all the work done. Aspect of news thanks

**Comment by derlaft** [comment]
Hello there. I am ready to donate my Pebble 1 to any active contributor. It is pretty damaged an has a dead zone on a screed, but still working.

**Comment by ashimokawa** [comment]
@derlaft 
This could be interesting for @cpfeiffer , as he does not have a pebble.
Carsten, interested?

**Comment by ashimokawa** [comment]
You can donate via liberapay

https://liberapay.com/Gadgetbridge/donate

**Comment by gianlucapir** [comment]
Thanks, I have already done last week, the inscription started to donate
-------- Messaggio originale --------Da: Andreas Shimokawa <notifications@github.com> Data: 29/08/17  23:57  (GMT+01:00) A: Freeyourgadget/Gadgetbridge <Gadgetbridge@noreply.github.com> Cc: gianlucapir <gianlucapirrone75@gmail.com>, Comment <comment@noreply.github.com> Oggetto: Re: [Freeyourgadget/Gadgetbridge] how to donate? (#14) 
You can donate via liberapay
https://liberapay.com/Gadgetbridge/donate

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Freeyourgadget/Gadgetbridge","title":"Freeyourgadget/Gadgetbridge","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Freeyourgadget/Gadgetbridge"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ashimokawa in #14: You can donate via liberapay\r\n\r\nhttps://liberapay.com/Gadgetbridge/donate\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Freeyourgadget/Gadgetbridge/issues/14#issuecomment-325816574"}}}
