### ISSUE TITLE
[bip] please whitelist 38532 and 32576 firmware

### ISSUE THREAD

**Issue by ThomasWaldmann** [Freeyourgadget/Gadgetbridge#1459]
I tested them, they didn't brick my watch nor did I notice anything else unusual yet.

1.1.5.12 = 38532 from mi fit 3.5.8

1.1.5.16 = 32576 from mi fit 3.5.9

I updated the wiki page accordingly.

**Comment by ashimokawa** [comment]
@ThomasWaldmann 
Done.

1.1.1.12 was already whitelisted but not the latin version which you referred to. Latin has Spanish,Russian,English(?) while the normal firmware has English and Chinese. That changed during time, so I am not sure if it is still correct. I do not keep track of the latin version because it forces to use the latin font which has Umlauts but no Japanese characters. 

This is another thing which we should somehow handle

**Comment by ThomasWaldmann** [comment]
IIRC:
- i tried the latin version (assuming it has better non-ascii support, but i still wanted english / german), but then it talked spanish to me although i configured english, so that didn't last long.
- what I gave were the checksums / infos for the non-latin version, which I used in the end to have something speaking english to me.

**Comment by ashimokawa** [comment]
@ThomasWaldmann 
1.1.5.12 = 38532 from mi fit 3.5.8 is definitely for the latin version

**Comment by ThomasWaldmann** [comment]
OK, maybe that one was from my very first try, before noticing that it talks spanish.
