### ISSUE TITLE
Gadgetbridge - Design Patterns - Thesis Survey

### ISSUE THREAD

**Issue by MarcelTUC** [Freeyourgadget/Gadgetbridge#1591]
Ladies and Gentlemen,
as part of my master thesis at the TU-Chemnitz (Germany) in Applied Computer Science (Professorship Operating Systems, Supervision Dr. Marcus Hilbrich) I search for design patterns in Open Source Android applications and investigate how they got into the source code. If you don't know what design patterns are, that's no big deal. You can still support me.

One of the applications investigated is the app "Gadgetbridge".
If you are or have been a contributor to this app, I ask you to complete this survey.

If you complete the survey, you will help me to assess how well Android application developers know about design patterns and how they get into the source code.
The questionnaire takes about 15 minutes to complete and is available in English and German.

Please fill out the questionnaire now: http://bit.ly/2OJBBBl

Thank you very much for your support!

Yours sincerely,
Marcel Müller
marcel.mueller@s2013.tu-chemnitz.de

---- German Version: ---

Sehr geehrte Damen und Herren,
im Rahmen meiner Masterarbeit an der TU-Chemnitz (Deutschland) in Angewandter Informatik (Professur Betriebssysteme, Betreuung Dr. Marcus Hilbrich) suche ich nach Entwurfsmustern in Open Source Android-Anwendungen und untersuche, wie sie in den Quellcode gelangt sind. Sollten Sie nicht wissen, was Entwurfsmuster sind, ist das nicht schlimm. Sie können mich trotzdem unterstützen.

Eine der untersuchten Applikationen ist die App "Gadgetbridge".
Falls Sie Mitwirkender an dieser App sind oder waren, bitte ich Sie, diese Umfrage auszufüllen.

Wenn Sie die Umfrage ausfüllen, helfen Sie mir einzuschätzen, wie hoch der Bekanntheitsgrad von Entwurfsmustern bei Entwicklern von Android Applikationen ist und wie die Entwurfsmuster in den Quellcode gelangen.
Die Beantwortung des Fragebogens dauert nur ca. 15 Minuten und er ist in Englisch und Deutsch verfügbar.

Bitte füllen Sie jetzt den Fragebogen aus: http://bit.ly/2OJBBBl

Vielen Dank für Ihre Unterstützung!

Mit freundlichem Gruß,
Marcel Müller
marcel.mueller@s2013.tu-chemnitz.de

**Comment by IzzySoft** [comment]
Afraid that, as this is a privacy focused project, only few users are willing to click an insecure (`http`, not `https`) link to a camouflaged (`bit.ly`) URL requiring at least 3 trackers (bit.ly, Cloudfront, Google Analytics) to reach an unknown site (as the URL was camouflaged) and spend 15min on a survey they might not even personally be interested in (what does the average user care about "design patterns" – and how does that help Gadgetbridge?).

So maybe you could take the privacy approach into your thesis keeping the amount of data collected and third parties involved to a minimum? That's one of the design patterns used here, by the way: Gadgetbridge keeps third parties out. It doesn't even have the permission to access the Internet. It doesn't *talk* about privacy – it ***lives*** privacy.

**Comment by MarcelTUC** [comment]
Dear Mr. IzzySoft,
Thank you very much for your feedback. The use of bit.ly in this case is due to the simplicity of short URLs. I am happy to provide you with the original URL: https://bildungsportal.sachsen.de/umfragen/limesurvey/index.php/158474?newtest=Y&lang=en (you see: with https)
I agree with you that bit.ly uses various trackers. In my case, they help me to see if my post/email has been seen at all.
Furthermore, I agree with you that this survey is of no use to Gadgetbridge itself. This survey is not obligatory for you. However, I had hoped to encounter people who would like to help me. 

Thank you for suggesting that I should include privacy in my work. I will definitely consider writing a chapter about it.

**Comment by IzzySoft** [comment]
I guessed those reasons. One we can disregard: people can click the URLs here, so no reason to have them that short. And Bit.ly understands HTTPS, so that part could be fixed easily. Leaves the statistics part – for which I might have a solution for you as well: try [Frama.link](https://frama.link/). FramaSoft is a privacy focused organization which offers quite a lot of privacy friendly alternatives to "well known services" and always the first place I check when looking for such (Searx: "Framasoft <service>", e.g. "Framasoft link shortener" – or doing a <kbd>Ctrl</kbd>-<kbd>F</kbd> [here](https://degooglisons-internet.org/en/alternatives/) :wink:

for the second paragraph: apologies if I sounded "ranting" – but this place usually is about solving issues with Gadgetbridge (or requesting features for it). But yes, where should you ask… So I assume you will update us here where the thesis is published (when it's done), so we can read what you write about Gadgetbridge?

Last: Thanks for picking up and including a chapter on privacy! For many of us this is an important part of "design patters" in software that too often is either overlooked completely, or at least given a much too low priority – while we feel it should be (one of) the most important item(s). In this context: 🙇 to the website admin of the server hosting your survey: no third party stuff, good work! Also nice to see a compact and clear privacy policy – though I wonder how "your data will be deleted and stored inaccessibly" does technically work: how does one store deleted data? 😄

So: All the best for your thesis!

PS: After having checked the survey, I'm not sure how valuable input from non-developers will be. I could only always check "never heard of this" and "cannot give information" 🤔

**Comment by ashimokawa** [comment]
This is spam

**Comment by ashimokawa** [comment]
https://github.com/search?q=Design+Patterns+-+Thesis+Survey&type=Issues

**Comment by MarcelTUC** [comment]
Hey @ashimokawa ,
sorry but this is not spam.
In my work I examine 24 apps, and if I can't find a contact email address, I post this as a GitHub issue.

@IzzySoft 
If you fill out the survey, at the end there is a field where you can insert you e-mailadress if you want to receive a digital copy of my thesis. :)
And thanks for your wishes!

**Comment by IzzySoft** [comment]
Thanks, but as I already stated: I'm no Android developer. So I filled the survey (mostly with blanks, yes) – and its analysis will have not much meaning to me (blanks again). I've got enough to do already, so I won't have time to spend on this, sorry.
