### ISSUE TITLE
New Mi Band model 1S to potentially support

### ISSUE THREAD

**Issue by chrisvella** [Freeyourgadget/Gadgetbridge#162]
I figure someone here may be interested in this: http://www.cheesynode.com/news/new-xiaomi-mi-band-now-appearing-on-mi-com/

New model includes a heart rate sensor.

**Comment by cpfeiffer** [comment]
Thanks, certainly very interesting!

**Comment by cpfeiffer** [comment]
Activity data synchronization will be supported with 0.8.1 (#205).
Heart rate reading is generallyy working, but either my firmware or my device is broken, because I only get 0 as value. Of course, there could also be a bug in the code, but I doubt it, because the green lights actually light up, so a measurement happens.

**Comment by cpfeiffer** [comment]
I'm closing this, because the following generally works with 1S (with a recent firmware):
- activity tracking
- alarms
- firmware update
- heart rate measurement

Concrete new features will be tracked in separate tickets, e.g. #178 (more to come).
