### ISSUE TITLE
Equivalent Gadgetbridge app on Linux server or sync smartwatch with two sources

### ISSUE THREAD

**Issue by timofonic** [Freeyourgadget/Gadgetbridge#194]
Hello.

I want to make my own portable server and I would like to have a notification device. This is going to be my smartwatch.

But I also want to use it for my mobile. Are there any possibility to share the same device between both systems? The server is going to have a bigger battery, so I would prefer it to be the main device.

Kind regards.

**Comment by ashimokawa** [comment]
@timofonic 
Interesting idea.
However I think there are some situations where is would be problematic to let both devices generate protocol packages. That's why I think the following would be a good idea (assuming you only need notifications):

Write a linux application that communicates with a "to be created" Android app via IP(TCP or UDP). That app will then generate notification intents which are already picked up and forwarded to the pebble by Gadgetbridge.

The reason to not listening to TCP or UDP in Gadgetbridge directly is that we do not want internet permission.

It might be best if we use the (spoiler) "Gadgetbridge Addon App" with internet access we are planning for things like whether updates etc for that. It should be fairly simple.

Just some ideas... If you have the neccessary knowledge you also can just do what you need alone. You do not need to patch Gadgetbridge for the plan I outlined.

**Comment by cpfeiffer** [comment]
You may have a look at https://community.kde.org/KDEConnect which forwards notifications from mobile to desktop (among many other things).

**Comment by danielegobbetti** [comment]
Long time no update and is not a GB issue. Closing.
