### ISSUE TITLE
Allow using Mi Fit while Gadgetbridge is running (but disconnected)

### ISSUE THREAD

**Issue by zimonish** [Freeyourgadget/Gadgetbridge#196]
There should be a method in Gadgetgridge (GB) to terminate process totally. I always need to go to process manager and kill a background Gadgetbridge process to be able to use Mi Fit with Mi Band (MI1A). Simply "disconnect" from Gadgetbridge do not work. 

Miminally a "terminate" command to Gargetbridge menu, but preferrably when going out from the GB with Android Back-button several times, it could ask (optionally) would one want to totally terminate (also background processes). If this is optional, it could be asked in "Mi Band Settings" like "Keep activity data on device (yes/no)", ....  "Terminate totally on exit (yes/no)"

And sometimes I need to unpair from Mi Fit and re-pair, if I have forgotten to kill Gadgetbridge and Mi Fit tries to use the band in the same time.  

Gadgetbridge and Mi Fit do not mix very well. But Mi Fit does have some more clear visuals about activities and sleep time. Still I would like to experiment and support Gadgetbridge development.

**Comment by ashimokawa** [comment]
@zimonish 
There is a "quit" option on the main menu. It terminates all activities and the service. Isn't that enough?

Unfortunately Gadgetbridge will always come back like a zombie because of the NotificationListener part. We cannot enable that during runtime unfortunately, there is no way.

But for your Mi Fit problem,if disconnecting is not enough, it is a bug and should be fixed.

**Comment by zimonish** [comment]
Oh, yes, it works, with v0.7.0 at least. Could it be it didn't work with v0.6.9 or .hmmm...I am not sure now. Now it works though. 

Yet, would be helpful to have it Quit with backbutton, if enabled in GB settings.

To add a feature to this issue then... how about warning, if GB finds "Mi Fit" is running when GB is started. I guess it cannot terminate/kill "Mi Fit" unless running as root, but it could warn at least an user need to terminate "Mi Fit" first.

(I have some issues because I have now both, MI1A and MI1S, and MI1S is not working so well with GB, but there is a issue-thread about it already so better handle those there.)

**Comment by ashimokawa** [comment]
@zimonish 
I am not sure if it is possible to "detect" whether some process is running. I hope it is not possible security-wise! But who knows, Android sucks at security.

About issues with Mi Band, personally I can't really help because I have written zero of the Mi Band code and I do not even own a Mi Band.

**Comment by zimonish** [comment]
Well, I have unrooted Note3 and there is for example "OS Monitor" Open Source app (found from F-droid) which is able to show all running processes and their CPU-usage.  
And yes, I think also it may be a security issue, but also in Desktop Linux any user can see any running processes (ps ax).

**Comment by cpfeiffer** [comment]
AFAIR one must still manually connect the device once when Gadgetbridge was closed. I.e. when you quit Gadgetbridge and then a notifications comes in, it won't automatically connect to the Mi Band.

At least if you have the option unchecked to automatically connect when bluetooth becomes available.

**Comment by cpfeiffer** [comment]
@zimonish Would you like to open a feature request for those lacking features or presentation of activities and sleep time?

**Comment by cpfeiffer** [comment]
@zimonish And I'd really like to understand what causes the interference with Mi Fit. Disconnecting the band should really be sufficient.

Maybe a bluetooth snoop could help us understand the problem. Or a gadgetbridge log or a logcat could point us to the root cause. I'd rather make Gadgetbridge and Mi Fit coexist nicely instead of telling everyone about quitting one or the other.

**Comment by zimonish** [comment]
I already submitted one gadgetbridge.log in this another thread:
https://github.com/Freeyourgadget/Gadgetbridge/issues/178#issuecomment-168559348
https://github.com/Freeyourgadget/Gadgetbridge/files/76599/gadgetbridge.log.zip

I have to learn to how to do Bluetooth snoop, but yes, I will provide as much information as I can. If there is a good step-by-step (for dummies) instructions, URL or instructions here somewhere would be nice.

As I mentioned, I have both Mi1A which is somewhat working with GB, and then Mi1S which is not able to sync correctly. GB can be made to recognize Mi1S only by providing BT MAC in the MiFit special-settings of GB configuration.

I can open a new ticket about the  Mi1S connecting and syncing issues later. There is already the said thread about supporting Mi1S heart-rate sensor, but basic syncing with Mi1S is neither working as it is with Mi1A.

**Comment by cpfeiffer** [comment]
@zimonish Thanks for your help in tracking these issues down. We need to have separate tickets for these distinct issues for each device, so that we don't get lost in all those logs, different devices, and different problems.

So, when you manage to create a logcat (for a start) of Mi Fit not working because Gadgetbridge is running, please attach it here. Maybe the logcat is already sufficient; otherwise we'll tackle the bluetooth snoop. (Basically you enable the developer options in the settings dialog and there check "Enable Bluetooth HCI Snoop protocol".)

Second, for your Mi 1A  problems, please open separate ticket(s).

And third, for the Mi 1S syncing, please also open a separate ticket, because #178 really is about the heartbeat stuff.

This will make it a lot easier for us to tackle these issues.

**Comment by zimonish** [comment]
The problem with Mi Fit will always be, that Mi Fit will flush the date from Mi Band if it reads it. And then there is nothing left for GandgetBridge to read. So it may still be a good idea in GB just to notify user maybe "Mi Fit" process should be terminated. Or then "Mi Fit" developers need to be convinced to also provide "do not delete data from the band"-feature.

Could I use this issue ticket for Mi1S syncing problems
https://github.com/Freeyourgadget/Gadgetbridge/issues/162  ?
It is basically just talking about support for Mi1S.

**Comment by cpfeiffer** [comment]
Right - we cannot get any data when Mi Fit deletes it. But Mi Fit should be able to connect to the band even if Gadgetbridge is running (when disconnected). So, yes, it would be a nice feature to check for vendor apps running in the background. Maybe we could even detect this differently, by checking if the bluetooth device is already "busy".

I just opened ticket #205 for the sync problem.

**Comment by zimonish** [comment]
I tried now to use Mi Fit when GB was in the background and Mi Fit succeeds to read from the band OK. 
I DID have "Connect to device when Bluetooth turned on" setting set "ON" always in the start and just recently changed that to "OFF", so that may have caused the problems with Mi Fit before. Also GB was then earlier version.  

There should be a Linux/Android driver with API for every of these fitness bands, working by a server-client-paradigm, so all apps which use some band could access the data even at the same time. Like there is a driver for GPS and many apps using location data can be run at the same time.
It could even be useful to connect to the band from a desktop Linux PC, so a working driver for a desktop Linux could be written and then be ported to Android.

**Comment by cpfeiffer** [comment]
Yes, indeed, a common driver/API would be nice. If you can convince some application authors to join forces, feel free to ping us again.
