### ISSUE TITLE
Notifications from MiBand

### ISSUE THREAD

**Issue by Schmetzler** [Freeyourgadget/Gadgetbridge#211]
Is it possible to get any notification from the band itself?
(Maybe the touch gesture)

Or what are the steps that should be done to check if there is something?
I am new to this stuff but I would like to implement a watch feature (even if this means it needs connection to the app)

I guess I can start with the accelerometer data (like in #63) (but my guessing it that this is shortening battery life in huge amount)

I would even try to change the firmware... but I guess I would brick my device with such a thing (or has anyone an idea how to savely change the firmware) and would that need a rewrite or are there other tools useable.

**Comment by danielegobbetti** [comment]
Hi @Schmetzler , unfortunately we are not aware of any option to get notifications from the miband. If you find any, please let us know because that would certainly be interesting!

I'm closing this issue, if you choose to go the accelerometer data route, please go on in the other issue you already found.
