### ISSUE TITLE
Does Pebble Time Round work? maybe add list of sort of supported devices to readme or wiki?

### ISSUE THREAD

**Issue by Samarium151** [Freeyourgadget/Gadgetbridge#233]
Unclear to me what models are known to work.  Pebble round has known compatibility issues with many apps.  Will it work with gadgetbridge.

This is a great project.  I really appreciate the work the team has done to date.  I have very limited coding skills but happy to add documentation to wiki.  Help with activity measurements (I have some physiology expertise) and test.

**Comment by ashimokawa** [comment]
Pebble Time Round should work just fine. I tested with the emulator and I am quite confident it works with the real device. 

You are right, I should add that to a the readme.

**Comment by Samarium151** [comment]
Thank much! I may pick one up then.

**Comment by danielegobbetti** [comment]
Hi @Samarium151, we had to revert the FAQ page you added to the wiki because it contained wrong information. In fact several users (myself included) never used the official Pebble app for setting their Pebble up. It is entirely possible to buy a pebble and only use gadgetbridge. We should have documented that, and unfortunately didn't.

Thank you for your effort, but we must ensure that we have right information on the wiki.

For the time being we closed write access to the wiki, as we are looking how to best deal with documentation contributions. Unfortunately the wiki here on github is not well integrated. We have no way to check what was added by whom globally, and revisions are not integrated with pull requests, etc.

We will find a way to let you help us with your valuable information, especially regarding the activity tracking, but with the growing number of wiki pages we had to address this issue.

Thanks again!

**Comment by ashimokawa** [comment]
It was the "Device Setup" page that I removed. FAQ will also be removed since it contains copy and paste from README.md and questions that were never asked.

**Comment by ashimokawa** [comment]
Added "Getting started" to wiki, added list of supported devices to README

**Comment by Samarium151** [comment]
No problem I did want to spam issues with a million questions. That said I put in there what I had to do get device working.   From the current instructions as a new user I still can't figure out how to flash fw.  The pebble round appears as two separate devices on BT neither of which would connect.  Is the FW updaters a separate binary?  I can locate no option for it in 0.8.0.

**Comment by ashimokawa** [comment]
Instructions for flashing the firmware are on the wiki, including a link in the README. I don't know why you did't find it. Basically you just have to open a pebble firmware file (.pbz) for the file manager or download manager and chose "Gadgetbridge fw/app installer".

Also I have no idea why you could not connect to the non LE Pebble. The LE Pebble is not used for Android, not even by Pebble Inc. It should work and it always worked for me and @danielegobbetti
