### ISSUE TITLE
Pebble: Merge with NotificationCenter 

### ISSUE THREAD

**Issue by tristan-k** [Freeyourgadget/Gadgetbridge#26]
Is there any chance that Gadgetbridge picks up some of the features NotificationCenter provides?

https://github.com/matejdro/PebbleNotificationCenter-Watchapp
https://github.com/matejdro/PebbleNotificationCenter-Android

**Comment by ashimokawa** [comment]
I will have a look. Thanks for the links.

**Comment by ashimokawa** [comment]
My plan is to experiment with having Gadgetbridge communicate directly with the watch side of NotficationCenter.

**Comment by tristan-k** [comment]
There are some others opensource applications for pebble which would also be enriching the user experience. Is it generaly possible to run pebble applications made for android (also called Companion Apps) with Gadgetbridge?

**Comment by ashimokawa** [comment]
For NotificationCenter I would prefer to implement communication with the watchapp directly in Gadgetbridge.

For other apps, I will have to think about implement the same interface that Pebble provides in their official App, so that the companion apps "just work".

I am not sure if companion apps always need an additional .js file which is contained in the pbw and runs inside the official app (some watchapps/watchfaces provide these).
In that case it would be harder to do.

I never used the official App, have to do some more research to understand their concepts.

BTW, which other opensource applications do you mean?

**Comment by glitchphan** [comment]
I had contacted the author of NC about the possibility of Pebble Dialer working with Gadgetbridge. He said that 'appmessage protocol' is required. Is this something that Gadgetbridge could support? He did say that NC would also need developer connection, but Pebble Dialer just needs appmessage.

**Comment by ashimokawa** [comment]
Appmessage protocol from external apps such as "Pebble Dialer" is planned but has not been started yet. See #106

**Comment by ashimokawa** [comment]
I will close this issue since it should just work if #106 has been fully implemented, currently it is work in progress.
