### ISSUE TITLE
auto connect on notification for mi band

### ISSUE THREAD

**Issue by rajeevn1** [Freeyourgadget/Gadgetbridge#265]
I would like the app to auto connect on a notification that should be delivered to the band. This will help in 2 ways

i)  no need for a persistent notification to keep the app running

ii) if i walk away from the phone for a few minutes (and the app disconnects) I will still receive all future notification without manually connecting.

**Comment by cpfeiffer** [comment]
This is exactly what we're doing. Whenever a notification comes in, and the band isn't connected anymore, it will be connected automatically and the band will vibrate/blink.

Keep in mind is that this only happens when the band was previously manually connected, but got disconnected. When you start Gadgetbridge without connecting, not automatic connection will happen.

Can you check if this works or not, and if it does not work, provide a logfile?

**Comment by rajeevn1** [comment]
It does not seem to work.  adb logcat *:W attached. Also,  Please confirm the reason for persistent notification, and if it is ok to block it after whitelisting the app for battery optimization.  Thanks.

http://pastebin.com/gDXBw0cy

**Comment by cpfeiffer** [comment]
Sorry, the logcat does not really help -- can you please enable logging in Gadgetbridge's settings, restart Gadgetbridge and try again? Thanks!

The persistent notification is necessary to be able to run a "foreground service", i.e. a service that cannot easily be killed by the OS. We need the service to stay alive to maintain the connection to the device.

And do not worry about battery usage -- Gadgetbridge is **very** friendly to battery. It isn't even listed in the battery statistics even though it is running all the time.

**Comment by rajeevn1** [comment]
debug log: http://pastebin.com/XxHjEtfj

**Comment by rajeevn1** [comment]
it does work with version 0.9.1. closing.
