### ISSUE TITLE
Support for Amazfit - Miband 2

### ISSUE THREAD

**Issue by computerlyrik** [Freeyourgadget/Gadgetbridge#274]
Amazfit is something like "Miband 2"  - see http://www.amazfit.com/

It supports 
- Vibrating
- Steps
- Sleep
- NO Heartrate

My "Moon Beam" Specs:
- BT-Name: "MI"
- BT-Mac: 88:0F:10:25:6F:15
- BLE-Scanner shows many of the known Characteristics as MiBand Mi1A and Mi1S
- App sees the Device (Due to Mac-Filter is "88:0F:10" for Mi1A) but pairing does not work - my "white Donut" does simply not vibrate.

Tested and working with original "midong" -App from Play store.

Any ideas how to approach this device?

**Comment by cpfeiffer** [comment]
What you can try is manually pairing the device with the android pairing dialog and check if Gadgetbridge can the connect to it. Make sure that the original app is not running.

If this doesn't work, enable logging (can be tricky at the moment, we really need to fix this) and attach a log file. If that doesn't reveal anything, try to get a bluetooth snoop of the original app (where it causes a pairing with the device).

**Comment by computerlyrik** [comment]
Logging does not work.

My phone does not support a SDCard so Logging fails as DB Export with 
"No writable external Directory found"

This is really bad for developing.

Am 03.04.2016 um 20:31 schrieb Carsten Pfeiffer:

**Comment by bigretromike** [comment]
Mine phone also dont support SDCard but that dont prevent me from copying log file to pc

**Comment by computerlyrik** [comment]
I have installed CyanogenMod 12.1 and GB current master (0.9.3-based).

I will try breakpointing the directory-resolver next weekend.

Am 04.04.2016 um 12:14 schrieb BigRetroMike:

**Comment by cpfeiffer** [comment]
If you use Android Studio, you get all log output in the "Android Monitor" view.

**Comment by cpfeiffer** [comment]
BTW, if you don't have an SD card, shouldn't you have an emulated external disk?

**Comment by Spleeeno** [comment]
fyi on sony devices (z3c here) the log file gets dropped into data/data instead of sdcard.
so "AF" did show up in discovery, tried pairing but that didnt work after 2 min as far as feedback from the device goes - although I have no idea exactly what kind of feedback even the official app would produce.
had AF in the device list afterwards, tried connecting like 4 times - the first time took ages, I aborted that one and on the 3 times after that it seemed to connect (the icon turned blue) a firmware number flashed up for a split second but it quickly jumped back to not connected - but the info button on the right side stays and the HW just returns "?".
log attached.

**Comment by cpfeiffer** [comment]
@Spleeeno thanks for the logfile! I've made a quick fix that might help. Please report back if this makes it work. No support for firmware update of course, but other things might work as is.

**Comment by Spleeeno** [comment]
so maybe its just me - but I cant get the logging to work with 0.9.7?
but as expected: the pairing didnt work ;)
btw, the "pairing with $mac" screen has a white background, even when Im on the dark theme.
Most people see that thing like once so I doubt it bothers anyone, but now you know :D

**Comment by cpfeiffer** [comment]
@Spleeeno Logging configuration was broken in 0.9.6, but 0.9.7 should have fixed this. Did you try toggling the setting in the preferences in 0.9.7? Maybe your devices lacks an external sd card and somehow the "emulated external sd card" is not properly configured on your rom?

Do you mean the regular Android pairing dialog? This one is outside of Gadgetbridge's control, so you would need to set a systemwide dark screen to have that dark, AFAIK.

And yes, at the moment all activity data is in a single database table, and since Amazfit and Mi Band 1S share the same "provider", the activity data will be shared for them as well. This will be fixed in the db-refactoring branch where we support different activity data for every single device.

**Comment by cpfeiffer** [comment]
@danielegobbetti just said that he had to force-close and restart Gadgetbridge in order to enable logging again after having disabled it.

I'll have another look at this, even though I can swear it worked fine for me when I tested it.

**Comment by cpfeiffer** [comment]
So, if you enable logging, then force-close and restart Gadgetbridge, you should get a log file. Would be great if you could post one, so we can find out what happens.

**Comment by Spleeeno** [comment]
its the "pairing with $mac - when your mi band vibrates and blinks, tap it a few times in a row" screen - kinda doubt the cm13 android pairing screen would give me tips about the miband when its an amazfit thats pairing ;)
as for logfile locations: on 0.9.6 it was /data/data/nodomain.freeyourgadget.gadgetbridge/files/GB_LOGFILES_DIR_IS_UNDEFINED/gadgetbridge.log, BUT starting with 0.9.7 its finally on the /sdcard/.
so...how dare you make it use the the right behaviour and confuse me being used to the quirk! :D

anyway, log attached. the behavior is still pretty much the same as with 0.9.6
[gadgetbridge.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/283851/gadgetbridge.txt)

**Comment by cpfeiffer** [comment]
Great, thanks for the log! Will prepare a fix later.

**Comment by cpfeiffer** [comment]
@Spleeeno we try hard to get the "external files directory", i.e. a writable directory on the sdcard, or emulated sdcard. But from 0.9.6 to 0.9.8 nothing changed in this regard...

Anyway, if you can, please test the current version (not the 0.9.8 release). If you need an fdroid release, we could spin 0.9.9.

**Comment by cpfeiffer** [comment]
Hmmwait. There's more problems. Could you try with your current version what happens when you change the wear location in the preferences, connect again and post the log?

**Comment by ashimokawa** [comment]
@cpfeiffer 
I would like to clean up the mess I did in master a tiny bit before releasing.
Also I would like to name it 0.10.0
Just because we have a new permission, and we touch the pebble timeline for the fist time, even though it is not a very useful feature.

**Comment by Spleeeno** [comment]
k, switched around the wear location
[gadgetbridge.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/285361/gadgetbridge.txt)

**Comment by ashimokawa** [comment]
@cpfeiffer 
while reading the log don't be surprised by the "got connection attempt" it is the new code in
BluetoothConnectReceiver.java
Maybe we should not enable the broadcast receiver before the first successfull initialized attempt, or restrict this one to pebble, or something else ;)
I didn't know the Mi Bands would somehow do incoming connects...

**Comment by cpfeiffer** [comment]
@Spleeeno Alright, thanks. Unfortunately it's the same problem. So either
- AmazFit does not support setting the wear location or
- the init sequence is somehow different

Looks like it's taking a little more time to get this baby running.

**Comment by cpfeiffer** [comment]
@ashimokawa yes, it's already in the logs. Not quite sure yet what to do with it :-]

**Comment by Spleeeno** [comment]
well, guess I'll try out the mi app for now.
btw - bit unrelated - any way to use those without an xiami account?

**Comment by cpfeiffer** [comment]
@Spleeeno No, you would have to hack your way around registration.
If you could compile GB yourself, we would have a much faster experimentation/feedback cycle. We could have a chat and try out various things.

If you'd be willing to do that, we should write up some instructions how to set up the environment. 

Or maybe someone is good with docker/lxc? A quick search reveals this:
- http://reul.space/blog/running-android-studio-from-a-docker-dot-io-container/
- https://github.com/yongjhih/docker-android-studio

**Comment by Spleeeno** [comment]
well, I know jack shit about java - but like a year ago I had android studio up and running on archlinux.
cause even without much knowledge: renaming and stripping googles wear watchface example to a bare naked digital timepiece wasnt that hard ;) but the ssd crashed and I hated wears gapps dependency - so I gave the lg g watch r to a friend and havent bothered since...
If I have enough time during the week I'll probably install studio via aur and setup git and all that.
kinda related: do you guys have any experience with using the emulator with bluetooth usb dongles?

**Comment by cpfeiffer** [comment]
I have used a bluetooth usb dongle with MiBanda when Gadgetbridge did not exist yet. Haven't done anything with the emulator yet.

Next release will *not* set the wear location for amazfit -- maybe it is the reason why initialization fails. I doubt it, but we will see.

**Comment by cpfeiffer** [comment]
And you don't need to know any Java -- I could guide you or even commit the experimental changes into a separate branch that you could pull.

**Comment by ashimokawa** [comment]
@Spleeeno
0.10.0 is out in f-droid
Could you give it a try?

**Comment by Spleeeno** [comment]
k, tried it with 0.10.0 - the only thing new is that the status goes to "waiting for retry" after the first failed connection attempts - it tries again, and fails and stays at disconnected.
[gadgetbridge.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/295964/gadgetbridge.txt)

**Comment by cpfeiffer** [comment]
Please test with 0.11.2 -- it's very well possible that the fix for #349 also fixes this.

**Comment by cpfeiffer** [comment]
Now that we have some Mi Band 2 support, we might resurrect this one. But I need a log with a recent Gadgetbridge so that we at least see which services and characteristics are available.

**Comment by cpfeiffer** [comment]
I don't think we will support this device anymore. If there is any further interest, feel free to reopen it.
