### ISSUE TITLE
MI Band: support for setting alarms

### ISSUE THREAD

**Issue by cpfeiffer** [Freeyourgadget/Gadgetbridge#28]
The user should be able to set alarms for specific times. MI alarms are supposed to work even without a bluetooth connection.

**Comment by danielegobbetti** [comment]
As stated in another message, I am studying the protocol wrt this feature.

**Comment by cpfeiffer** [comment]
Cool, looking forward to that :-)

**Comment by danielegobbetti** [comment]
Hi, I think I have identified the messages and the different values. I am setting alarms on my miband since a vew days and they seem to work. What is missing wrt the communication with the device is:
- I am using more than one alarm at the same time but I am not sure of the upper limit (yet)
- I am unsure about the unit of measure of the "smart wakeup" byte in the message
- I am unsure about the usage of specific dates in the message (a whole "calendar" object must be passed, but only HOUR_OF_DAY and MINUTE seem to be used)

What I did so far was adding a method to MiBandSupport (setAlarm) and calling it from the debug activity (in order to this I had to add an empty method with the same name to the PebbleSupport).

The parameters needed to set an alarm are:
- index (of the alarm on the device)
- enabled/disabled (boolean)
- calendar object (as sayed only HOUR_OF_DAY and MINUTE seem to be used, so perhaps is better to pass these around)
- smart wakeup duration (untested, unknown unit of measure)
- repetition mask (every monday, tuesday,...) is a bitmask of integers

I am unsure how to proceed since you are much better Java-coder than me and I am pretty sure I would put something in the wrong place :-)
What would be needed is:
- some kind of local storage for the alarms (they cannot be read from the device as far as I found out)
- an abstract class for holding the repetition patterns as constants (I think it would be a good approach, but I may be wrong)
- probably something else


I can commit these modification on my fork, but it's far from a pull-request. Could you help me with the aforementioned tasks?

**Comment by cpfeiffer** [comment]
Awesome! I'll try and experiment with your work at the weekend. For now just, a few comments:
1. also think that the alarms cannot be read from the device, so we need a local storage. We could use the SharedPreferences API for a start, because we don't have any database support at all, yet. We definitely need that in the near future, though.
2. the superclass GBDeviceProtocol is supposed to be used to handle device-specific protocol implementations. We currently do not have that for the Mi Band because it operates a little different than the pebble. But we could certainly create an abstract MiBandProtocol class that (for now) does *not* implement GBDeviceProtocol. Then we can move all magic byte sequences, etc. there.

Since your changes don't change any existing functionality yet, we can integrate them without a problem.
And don't worry, no need to be perfect from the beginning, small steps get us forward :-)

I you want to contiue to work outside the main repo and then submit "one big pull request", we can do that. If you reference this ticket number #36 in your commit, then they will automatically update this ticket, I think.

But you can also send several smal "work in progress" pull requests. This would lower then chance of merge/rebase conflicts.

I any way -- very cool :-)

**Comment by danielegobbetti** [comment]
Further info I gathered:

- I cannot set alarms on the device with an index > 2, hence I believe the maximum number of alarms is 3
- What I described as "smart wakeup" behavior in the comments is not right. I believe the band will vibrate once every 10 minutes until it detects a significant movement (perhaps a step?), this happens even if the "smart wakeup" byte is set to 0.

**Comment by ov3rk1ll** [comment]
@danielegobbetti: I've looked into this a bit an the Mi Fit app sets the "smart wakeup duration" to either 0 (unchecked) or 30 (checked) to it seems that both your statements are true (multiple of 10 and fires every 10 mins unit it reaches the set time)

**Comment by cpfeiffer** [comment]
Yes, AFAIU, setting the value to 0 means "normal alarm", exactly at the configured time.
The smart alarm would wake you up at most 30 minutes earlier in case you're in light sleep mode.

Don't know if the maximum amount of "early-minutes" is configurable via this value or if it's just 0 or 30.

**Comment by danielegobbetti** [comment]
Hi, I just pushed a working implementation against the current master at:
https://github.com/danielegobbetti/Gadgetbridge/tree/set-alarm

As said, the code works: alarms can be set, saved in the Shared Preferences and are correctly sent to the device (as far as I can tell),  but there are some issues for which I need help from more experienced devs, namely (I'm pasting the commit message below):

* The alarms are stored to and read from the Shared Preferences, but there is no persistence within the app (basically they are read and stored at every access)
* The alarm list is not updated when coming back from the alarm detail view (probably related to the point above), but the actual alarm is
* The alarms preference names is sometimes built by concatenating strings, which is not really safe
* There is no check in the alarm constructor whether the stored string is a valid alarm representation
* Even though only 3 alarms can be stored on the device, we could have more in the app and let the user choose which to sync
* In the alarm detail view XML some material* drawables are used, it's possible that these break on android version < 5
* ...

**Comment by cpfeiffer** [comment]
Very good job! I only tested this with Lollipop, so I don't know whether the material drawables make problems on Kitkat.

I'd love to have the independent of the Mi Band device, so that it could be used with the Pebble or other devices as well. In that regard, supporting more than 3 alarms would make sense as well.

But one step at a time :-)

Thanks a lot!

**Comment by danielegobbetti** [comment]
Thanks for testing and for the comments in the commit!
I tried to keep the miband-specific logic within MibandSupport (for istance the smart wakeup is a boolean within the alarm, and becomes "30" only in MibandSupport, same for the calendar manipulation that are Miband specific).

I'm starting to think that perhaps the alarms should be in the DB (if we want more than three) but this could be a future enhancement.

**Comment by cpfeiffer** [comment]
Yeah, most parts are already device independent, very good. And yes, storing them in the DB may be a good idea. 

From the amount of data, using preferences should not be a problem (this is just a couple of bytes), but we'd need some extra code for storing an number of structured elements via preferences.

OTOH, we need code for reading the DB as well, so I haven't made up my mind what's better suited for this task. IOW: choose what you prefer :-)

**Comment by cpfeiffer** [comment]
Oh and thanks for the updates :-)

**Comment by cpfeiffer** [comment]
Good job with the new update. Almost ready for prime-time :-)

**Comment by danielegobbetti** [comment]
I agree, with a couple of iterations more it could be merged :)

Thanks for the continuous feedback!
--

**Comment by danielegobbetti** [comment]
Closing now that the functionality landed in master.

**Comment by chrisvella** [comment]
Would it be possible to read alarms from the system?

**Comment by danielegobbetti** [comment]
On the phone side it should be trivial, the alarms are available through a content provider (at least on  android versions where the standard clock app is used) as outlined in [this](https://code.google.com/p/android-alarm-database/source/browse/trunk/src/com/android/alarmclock/util/AlarmDatabase.java) code.

The logic could be more intricated, though, because the band can only store three alarms at once, and we would need to deal with expired alarms etc.

Since this would be a feature that may be useful also for the pebble, I kindly ask you to open a new issue for this feature and if you could propose also a strategy for dealing with the system alarms (which one to transfer, when to delete them, etc.) it would be wonderful.

**Comment by ashimokawa** [comment]
To be honest, I have no idea why I would want to sync alarms from the phone to the pebble. I use my pebble for alarms but not my phone. Who would want to use both?

**Comment by tristan-k** [comment]
Would love to see a sync between the miband and the internal android alarms. Any progress?

**Comment by danielegobbetti** [comment]
@tristan-k this issue is closed since more than one year. Adding WONTFIX label.
