### ISSUE TITLE
Miband 1S: Reconnecting after connection loss

### ISSUE THREAD

**Issue by v1r0x** [Freeyourgadget/Gadgetbridge#293]
First of all I want to thank you for providing an open-source alternative to MiFit!
One annoying problem I have is that several times a day I lose the connection between smartphone and miband. This happens (at least most of the time) when I leave my phone at the desk (or anywhere else) and go to another room or to the other end of a (larger) room. If I now come back to my phone it doesn't automatically reconnect which is quite annoying. Thus I have to unlock my phone using a pattern instead of smart unlock and reconnect the miband in the gadgetbridge settings. Since I have to use my unlock pattern I'm not sure if this is a GB problem or an android problem, but I saw similar issues (#89 and #186) for pebble and wanted to let you know.

Keep up the great work!
regards
v1r0x

**Comment by cpfeiffer** [comment]
Interesting -- I had thought, the smart unlock function works when the bluetooth device is "nearby", not necessarily connected.

This is why I haven't added some kind of watchdog that repeatedly tries to reconnect the Mi Band; simply because it was not necessary. The connection is automatically established as soon as a notification arrives.

There is another option though: the Android Bluetooth API allows to use a connection mode that will automatically reconnect when the desired device is in range. There is no way to customize the reconnection behavior (how long, how often, etc., but it's all built-in, we just have to enable it (again). We had it enabled a while ago, and it caused some spurious connection problems, but maybe we can fix those instead of creating an own watchdog.

And we should make this mode optional with a preference.

**Comment by v1r0x** [comment]
I thought the same way. Unfortunately I don't have much experience in BT but if there is something I can do (logs, testing, etc) I'd like to help. Or help with the UI refactoring ;)

**Comment by cpfeiffer** [comment]
Any help is appreciated, especially in the UI area :-)

For a start, I'll make the (re)connection mode configurable.

**Comment by cpfeiffer** [comment]
Reconnection is now possible and enabled by default. It might take a while even after you're back in range, and it is not specified how long it will attempt to reconnect, but that's how it is with the Android BLE Api.

I think it's working quite well now.

**Comment by v1r0x** [comment]
Thanks for the quick fix! I'll test it as soon as I can.
