### ISSUE TITLE
Last seen battery charge level

### ISSUE THREAD

**Issue by bigretromike** [Freeyourgadget/Gadgetbridge#295]
Could GB remamber/show last known battery life level in device info when device is disconnected?
Mi Bands don't support showing battery level and there been twice cases that mi band battery died and I couldn't connect to it - that would be awesome to make sure it didn't died.

That way I could just tap (i) on the right and see that battery % was low

**Comment by cpfeiffer** [comment]
That would be possible, actually we deliberately *do not remember* the battery level atm. That's because the battery level will decrease over time and Gadgetbridge would show the wrong battery level. Maybe we could display it differently so that the user recognizes that this is not the current battery level.

However, my Mi Band always alerted me about low battery levels by blinking and vibrating, even without a connection to the mobile.

**Comment by bigretromike** [comment]
with so many application and notification that 'alerting' could be missinformative :-) 
Maybe a grey battery level/when not connected and black when its connected/current ?
