### ISSUE TITLE
An unusual request

### ISSUE THREAD

**Issue by ukadiyala** [Freeyourgadget/Gadgetbridge#298]
Hi Guys,

I'm building a windows app for the MiBand. I had reverse engineered the official APKs to understand the BLE protocol utilised by MiBand. I came across your library in a bid to understand how to retrieve activity data from the device. Great work guys. From one dev to another... You  have done a fantastic job with this so far.

My question here is what is the exact sequence of BLE commands one needs to execute to trigger the retrieval of activity data on the MiBand. I have gone through your code and notice you are calling the doPerform() method within FetchActivityOperation. Can you please help me understand some of the calls being made within this method? i.e. The expected behaviour from the device. 

Any help here would be appreciated. Thanks.

Regards,
Udhay

**Comment by danielegobbetti** [comment]
Hello and thanks for the kind words.
Regarding your project feel free to share a link to the repository of your free-as-freedom software in this issue, then perhaps you'll get some help there. Not having a windows machine available since a long, long time, I'm not going to be able to do anything to this end, though.

About our code, you are very welcome to add to our wiki all the details that are clear to you, as well as those who aren't, at which point we can chime in and clarify them.

Best of luck for your project, it's good to see open source software developed for windows!

**Comment by danielegobbetti** [comment]
closing this as no further info have been provided
