### ISSUE TITLE
MI Band: support for steps tracking

### ISSUE THREAD

**Issue by cpfeiffer** [Freeyourgadget/Gadgetbridge#31]
A user should be able to set the daily goal of steps. And the current value should be available for inspection.

**Comment by danielegobbetti** [comment]
I'm leaving this here since it's the closest issue I could find. I never used the official app that probably does a couple of things in the background hence I learned the following:
- if you set user info and daily data and the date/time was never sent to the band, it will start counting steps without taking care of the daily goal.
- as soon as you set the date, the daily goal tracking will start working (including the vibration at the point when you reach the goal etc.)
(That's why I found out how to set the date, by the way ;))

So the most important thing is not to forget to set the date when sending user info!

**Comment by 1337sup3rh4x0r** [comment]
I don't know if you noticed this project here:
https://github.com/KashaMalaga/XiaomiMiBand
They take apart and alter the original app. Maybe this can help with insights on what the original app does. Although it's in Smali and thus not entirely readable.

**Comment by danielegobbetti** [comment]
Hi @1337sup3rh4x0r indeed, thats how I found out how to set the time.

Fortunately for realtime steps and battery the procedure is easy, and other developers already implemented it in java as well.

Getting the activity data (including sleep) is a different topic: I am not aware of any open source code that is able to get the data, my naive approaches of getting the data from the device failed, hence I think the original smali must be studied for this. The settime method was < 50 lines of smali code, hence it was quickly done, I have no idea aboout the activity data: if you can take a look at the smali code and share some thought that would be really helpful!

**Comment by cpfeiffer** [comment]
@danielegobbetti Thanks for your input! We now set the time in the initialization phase during connection.

**Comment by animalillo** [comment]
a way to see walked steps?

**Comment by danielegobbetti** [comment]
Hi,

It's in master already and will be part of the next release. 
--

**Comment by danielegobbetti** [comment]
Feature released with version 0.4.5
