### ISSUE TITLE
Getting the sleep info and walking time.

### ISSUE THREAD

**Issue by AlexanderHryk** [Freeyourgadget/Gadgetbridge#311]
Hi all! I'm implementing simple fitness app for my university using the Mi Band 1S. Currently the app can measure the count of steps and heartrate... I need to know how to get **walking time** (this info is saved in miband**???** or it calculated using steps and speed constant) and how to get **sleepdata** (deep and light phases). All i need is to know where from this info can be read (ble characteristic) and how to interpret it. I know that this features are implemented in your app, but your code is very difficult for me. I will be very glad if someone help me!

**Comment by danielegobbetti** [comment]
<old grumpy man voice>When I was younger, university assignments were supposed to be difficult and nobody helped me</old grumpy man voice> *sorry I couldn't resist* 😉

Jokes apart, I'll happily explain our code if you tell what you *specifically* find difficult to follow, so that you can fulfill your assignments. I'm not going to answer your assignments' questions for you, though.
Please consider also that our wiki contains a high level description of our code that may help you understanding what class does what.

If your project also involves writing a proof of concept software, consider open sourcing it and putting it online so that we can take a look at that as well.

 Best of luck for your project, and please keep using this issue, even though I am closing it now to clean up our issue tracker.
