### ISSUE TITLE
Location access from watchapps

### ISSUE THREAD

**Issue by IzzySoft** [Freeyourgadget/Gadgetbridge#327]
With v0.10.0 now requesting location access, I thought some simple location-based watchapps might work – so I've tried [Get Back in Time](https://apps.getpebble.com/de_DE/application/553329021b2b662f5b000069?dev_settings=true&hardware=basalt&is_browser=true&platform=android&query=&section=watchapps), which only needs the built-in compass plus the current location (at least it looks like that). Unfortunately, it sticks at "Initializing (Loading data)", and seems unable to obtain the current location.

Do I miss something, or does GB not provide the location to watchapps? Of course it could as well be the watchapp wanting to load some other data from the Internet (e.g. have some server calculate the distance – though that's unlikely at least at this point, as no distance is yet to be calculated on first-call), before trying other alternatives I want at least to be sure about the location fact. As a side-question it would be useful to know what kind of data GB would provide a requesting watchapp to get an idea what's worth trying :)

Alternative candidates for "location and direction" most likely only needing the location but no Internet:
- [GPS Bookmark](https://apps.getpebble.com/de_DE/application/55775398691b9bc76e00007c?dev_settings=true&hardware=basalt&is_browser=true&platform=android&query=&section=watchapps)
- [Get Back To](https://apps.getpebble.com/de_DE/application/550bf37f1e540c856300005e?dev_settings=true&hardware=basalt&is_browser=true&platform=android&query=&section=watchapps)
- [Get Back](https://apps.getpebble.com/de_DE/application/52cae46a6126ce093f000064?dev_settings=true&hardware=basalt&is_browser=true&platform=android&query=&section=watchapps)

Side-question: Those apps might want the "exact location (GPS)", so we might need an option to "fake" a GPS location from a network location.

**Comment by danielegobbetti** [comment]
So far is only used for sunrise and sunset but I'll look into the watchface you posted to see if and how we can support it.

**Comment by danielegobbetti** [comment]
The last watchapp you posted doesn't require internet access, but I don't think that's possible, as apparently the webview geolocation object requires fine location permission [source](http://stackoverflow.com/questions/5329662/android-webview-geolocation), and this is used directly in watchapps' javascript code.
If we were adding a wrapper (to pretend we have fine location even though we don't) I fear it would be a bottomless pit we dig ourselves.

I'm not closing this, as I would like this to happen, but it's not high on the priority list.

**Comment by IzzySoft** [comment]
@danielegobbetti thanks for investigating that fast! Of course I am not aware of implications it might have elsewhere (I'm neither a Java/Android dev nor did I even skim over all the GB code). So I was of course not *demanding* anything but rather *suggesting* :)

Whether to use a wrapper to *pretend* we have a GPS source or really providing it is a different point. As GB already uses coarse location, adding GPS cannot be seen as such a big "privacy issue" (not saying the argument should be neglected). I'd be fine with both, but I cannot speak for others. And sure, not prio-1; if it comes one day I'm glad, if it takes a while I can live with that :)

**Comment by ec1oud** [comment]
It could be a preference anyway, right?  Allow watchfaces to access location, or fake it if not allowed.

**Comment by mrmarbury** [comment]
Hi,

I have another app here that does location lookup via a JS file [Departure Monitor](https://forums.pebble.com/t/watch-app-sdk2-departure-monitor/7894). I don't really know what has to be done here. But it would be really cool to use location and internet

Cheers,
Stefan

**Comment by ec1oud** [comment]
I guess maybe we could develop a universal companion which can provide data that most watch faces will need.

https://github.com/ec1oud/sologyr is one I'm developing: a watch face and Android companion app that go together.  (still buggy and half-baked so far)  But I was thinking it's silly that every watch face tends to need its own app.  The UUID is used to pair them up, right?  Presumably that's how gadgetbridge constructs an Intent to communicate with the correct companion app?  Guess I should read the source.

Even more silly: I have to calculate sunrise and sunset for myself even though GB is already putting them on the timeline, because there's no way for a watch app to access that, due to missing API.  But I think I will change it so the watch face does those calculations: all it needs is location, and it can persist that for use between connections, because otherwise the sr/ss times are lost whenever I switch between apps AND the phone isn't connected.  (Does anybody have any handy C code for that?  I'm using a Java library I found, for now.)

After the fitbit takeover, I wonder if the whole watch will end up being open-source eventually, either by them freeing it or by the community reverse-engineering it.  Then we could add features like location and sunrise/sunset and moonrise/set and tides and weather and timeline access built-in to the firmware (depending on features in GB or in a universal companion, but NOT depending on JS, thus closing the loophole that watch faces running unaudited JS might be tracking us).

Then again what might happen even sooner would be open-sourcing the original Pebble apps and the SDK.  Wouldn't that be cool... dare we hope?

**Comment by mrmarbury** [comment]
OffTopic: @ec1oud: Unfortunately i cannot help you with any C or pebble insights. But you might check the [pebble subreddit](https://www.reddit.com/r/pebble/) and search for "Archive" and "Panic Store" there are torrents and online mirrors of almost everything.

**Comment by danielegobbetti** [comment]
@ec1oud and everyone else I believe (but note that this is my personal view) that now that pebble Inc. isn't there anymore we **could** try establishing an API to provide uniform access to location, timeline and weather data. What I mean is that we (the readers, not only the GB core team) should discuss and outline how such an API should look like, and then GB would be a reference implementation of this API.

I believe we should gather GB team, android companion app developers and watchapps/watchfaces makers, then this could well be a "live" document where we agree on the priorities and implement in parallel both sides of it.

I'm not sure how the process would look like in detail, but if the interest is there I believe it makes sense to try coordinating the efforts.

**Comment by mrmarbury** [comment]
There is [this post](https://www.reddit.com/r/pebble/comments/5hkq5d/introducing_the_panic_store/) in Reddit where they do exactly that...gather up ressources for developing and alternative to the Pebble App so I think a good place to discuss this is over there. What do you think?

**Comment by IzzySoft** [comment]
Please keep in mind that at least when it comes to weather data, this would require the `INTERNET` permission – which, as we discussed multiple times already – is something GB itself should never request (I fully trust the GB team – but newcomers don't even know you).

I'm fully happy with those features to come, don't get me wrong. But they shouldn't be implemented into the main app. For reference, there's issue #302 :smiley_cat:

**Comment by danielegobbetti** [comment]
@IzzySoft regarding weather we have quite some tricks up our sleeves in the [weather branch](https://github.com/Freeyourgadget/Gadgetbridge/tree/feature-weather) ;-) but we're going slightly offtopic

**Comment by danielegobbetti** [comment]
FYI the soon-to-be-released version 0.18 allows configuration pages using clay to access the device position. The functionality is in master since a couple of weeks.
