### ISSUE TITLE
unable to update firmware for 1S

### ISSUE THREAD

**Issue by d-p** [Freeyourgadget/Gadgetbridge#369]
Hello,

my "Mi Band 1S" stopped to provide the hearth rate (always 0, no
blinking led on the band) some weeks ago.

It runs 4.15.12.10 Mi Band Firmware + 1.3.74.76 HR Firmware
(recommended) since I updated the firmware (successfully) a couple of
months ago (using CyanogenMod 12.1).

I did not care for a while.  Then I tried to reboot few times, check
the debug, rebind and so on.

At the end I tried to upgrade/re-flash the firmware (Now using GB
0.11.2 on CyanogenMod 13.0).

Unfortunately both version will fail:

- 4.15.12.10 Mi Band Firmware + 1.3.74.76 HR Firmware (recommended)
- 4.16.4.22 Mi Band Firmware + 1.3.76.22 HR Firmware

Note that there is a minor issue since the recommended version
4.15.12.10 is not recognized as supported by the installer, whereas
the wiki tells that it is.

The relevant part of the log (less time stamps, duplicate lines and
personal info) follows (please ask for the full log offline).

It was made with "Use low-latency mode for FW updates" off.  With on
it seems to fail early and not at the end.

I will not reboot the device and wait for your suggestions.  I will
happily try to void the warranty, if necessary! :-)

**Comment by d-p** [comment]
[gadgetbridge-redacted.log.txt](https://github.com/Freeyourgadget/Gadgetbridge/files/397650/gadgetbridge-redacted.log.txt)

**Comment by cpfeiffer** [comment]
Thanks for the report and the log. Unfortunately I don't have a good suggestion for your problem.
I've seen many broken Mi Bands already, but none of the problems were software-related or curable in any way. So far, the best option was keeping the band for the other functions (e.g. alarms, vibrations).

What you can try is:
- using another phone to reflash the firmware, although I doubt that it fixes anything, try both low latency and high latency mode. Try a few times, some guy reported it working the third attempt.

Maybe there are some more connection parameters that we could try to set in order to establish a more stable connection, but I have no idea if that is actually the cause for the problems.

In any way, good luck and keep us posted about your results :-)

**Comment by d-p** [comment]
Small update: a try with CM 12.1 was unsuccessful both with low and high latency.

**Comment by d-p** [comment]
Hello,

during this month I never rebooted the band and the heart rate was
always broken.

Yesterday I installed the new version 0.12.2 of Gadgetbridge.  The
heart rate started working.

Also the firmware update went well on the first try for the version:
4.16.4.22 Mi Band Firmware + 1.3.76.22 HR Firmware

By the way the app tells that this version is not supported but the
wiki says the version is recommended.  FYI the white list firmware
string is: 68158486

I do not know what the problem was, but now is resolved!

Best!

**Comment by cpfeiffer** [comment]
I added the number to the wiki and to the whitelist so that it will be recognized as "supported".

Thanks!
