### ISSUE TITLE
No sleep data since last update (v0.14.2)

### ISSUE THREAD

**Issue by 6arms1leg** [Freeyourgadget/Gadgetbridge#440]
Since the last GB update (v0.14.2), no sleep data is shown in any graphs – "Light Sleep" and "Deep Sleep" are shown as "Activity", so all graphs are essentially just green. I upgraded from v0.13.8, so I can't say where/when this was broken.
Tested with a Mi Band 1.

**Comment by rplevka** [comment]
same issue here. (mi band 1s). This has been introduced by the recent version (0.14.2)

**Comment by IzzySoft** [comment]
Confirmed on Pebble Time Steel as well, so it seems to be global.

**Comment by cpfeiffer** [comment]
It's fixed for Mi Band 1, I'm very sorry. Will release really soon.

**Comment by IzzySoft** [comment]
@cpfeiffer I hope you didn't mean it's ***not*** fixed for the Pebbles?

**Comment by cpfeiffer** [comment]
I only fixed it for Mi Band 1, and if it really does not work for Pebble either, it is a completely different issue (implementation-wise). Can you please open another issue for Pebble, because this issue is fixed for Mi1 and frankly, I have no idea where to look for the Pebble bug.

**Comment by IzzySoft** [comment]
@cpfeiffer with 0.14.3 at the doors, I guess I wait for that and see if it was "just a nasty side-effect" solved by that release. If not, I'll open a new issue and link here (as reference that you said it must be something different). Would be strange, though, that it happened at exactly the same time, wouldn't you agree?

**Comment by cpfeiffer** [comment]
Alright. I totally agree that it's strange, but code-wise there really is no relation.

**Comment by IzzySoft** [comment]
Agreed on that, too: I checked with your related changeset, and it touches MI code only. Well, let's see: 0.14.3 is already in the changelogs, the tag was created about an hour ago – so it's only a matter of days until it appears on F-Droid (should be there until weekend). If the bug is still there, and unless someone else filed it already, I'll do that then. Thanks for the heads-up!

**Comment by ashimokawa** [comment]
@IzzySoft 
I still have blue bars with my Pebble2

@danielegobbetti 
Is it normal that sleep has "holes", I mean no light sleep, no deep sleep, no green bars?

**Comment by IzzySoft** [comment]
@ashimokawa 

I have only the greens – so only the "holes" you've just asked Daniele for, or rather one big hole. Since I've upgraded from 0.13.9 to 0.14.2 (I've skipped the 0.14.0 due to F-Droid's delay), I see no sleep data at all. Waiting for 0.14.3 to pop up at F-Droid, and will open a new issue then if it's still empty.

**Comment by danielegobbetti** [comment]
@IzzySoft that is weird as I do see sleep and deep sleep as usual.
@ashimokawa it is indeed normal to have columns with 0 intensity during sleep on the activity graph if one sleeps well (which is not the case for me). The sleep pie chart should however show correct values, if this is not the case then there is something weird going on.

**Comment by rplevka** [comment]
I downgraded back to (v0.14.0) and the sleep data is being interpreted correctly. So it's definitely the last release and the issue seems to be just in the way sleep data is being interpreted.

**Comment by IzzySoft** [comment]
@danielegobbetti With a Pebble Time Steel? I see not a single blue dot, and the pie just shows an empty white circle, since I've updated GB to 0.14.2. I'd understand "little gaps when zoomed" (had them before), but the pie explicitly states 0 minutes.

Still waiting for 0.14.3 popping up at F-Droid. If you consider attaching an `.apk` to the releases, my offer concerning [my alternative repo](https://android.izzysoft.de/repo) still stands. Note I don't recompile, so signature would be yours then. Updated `.apk` files should show up in my repo then within 24h (every day around "now", my updater just finished its daily run half an hour ago).

**Comment by danielegobbetti** [comment]
No, but it would effectively be the first time that different models send data in different ways (and mind that also p2 is working). If you could send me the log rows that contain datalog - sleep (unsure about the exact syntax but if you filter for datalog you'll spot them) I can take a look.

**Comment by IzzySoft** [comment]
@danielegobbetti You've got mail. Attached you the entire logcat, starting last night before "bedtime" and ending now. In short: "health - steps" is there, but no "health - sleep". Bunch of "ignored timeouts", though.

Please let me know a) whether you need additional details and b) whether a downgrade to 0.14.0 would be safe (to cross-check). Thanks!

**Comment by danielegobbetti** [comment]
My bad (or bed, given the topic? :-) ), the datalog entries are called "overlay", not sleep... I'm checking your logs.

**Comment by IzzySoft** [comment]
See the second batch from today. 0.14.3 converts my sleep into sleepwalking now: 953 sleep samples get turned into 254 steps :scream_cat:
