### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by chr15m** [Freeyourgadget/Gadgetbridge#451]
Not sure how else to contact you, but I wanted to say thank you so much for this software. Absolutely wonderful. I use it every day.

**Comment by jjg** [comment]
I'm also very thankful to have found it in light of what's happening to Pebble, thank-you.

I would really like to port the functionality to Linux if possible, so I could build a Linux-based phone and keep using my Pebble :)

**Comment by alphatonic** [comment]
I would also like to thank the developer for this.

Even with Pebble gone i want to continue using my Time Steel for as long as possible.

**Comment by ardaozkal** [comment]
Pebble Technology Inc. going bankrupt is not really a concern for me, because a great majority of Pebble users are really brilliant people, who will probably do their best to keep their device working as long as possible. This project is just an example of that. It's amazing, and I want to thank you for showing me that I wasn't going overly hopeful of the community. 

I switched to gadgetbridge yesterday (pebble app was broken for me for a few weeks, I mailed support, they said they forwarded that to technical team, and that they'll reply in some time... I guess that time is 'never' now), and I've been able to use my pebble again thanks to this app. Thank you, again.

**Comment by GearDr** [comment]
I would also like to extend my appreciation. I'm not finished with owning a Pebble, and the way things are going, it's Gadgetbridge that's going to make that possible. Thank you for the time and effort put in for the sake of the community, and thank you for keeping alive the one smartwatch I ever truly wanted.

**Comment by IzzySoft** [comment]
I wouldn't have bought a Pebble if this project hadn't existed. So I hope you all don't get discouraged by the "ongoing politics": There probably won't be any more new Pebbles. There probably won't be many people with a Pebble-2 (to appreciate your efforts of the last weeks). There probably won't be many more firmware updates (if any at all). Please don't let that get you down too much! You're doing a wonderful thing here. Please keep that up – we all really appreciate it!

So a big thanks from me as well!!!

**Comment by ashimokawa** [comment]
@IzzySoft 
Yeah too bad, we put so much energy into this project and now pebble is gone.
But if my Pebble 2 fails and there is an alternative on the market (which I doubt because people don't care about battery), I will try to support that. Gadgetbridge is not Pebble only after all!
Hope it will last a few years though, the last Pebble was the best.

**Comment by Qwertie-** [comment]
Just want to leave my thanks as well, wonderful project and more relevant then ever now. Really hoping pebble open sources the firmware for their watches :/

**Comment by Jojonintendo** [comment]
I would like to join the others thanking you. I'm a Pebble Time and (soon) Mi Band 2 user, and I'm really grateful for what all the developers are doing. The community is great too, and very involved and willing to help. I think this project is really needed now more than ever, so that we can use our devices without giving out any unwanted data.

Anyway, very good job guys, continue working like this! It is amazing!

**Comment by cpfeiffer** [comment]
Thanks for all the kind words, much appreciated 
:-)

**Comment by clemens23** [comment]
I also say thank you very much, i changed from the pebble Cloud to GADGETBRIDGE and All of you do a good Job. Thank you!

**Comment by zlash** [comment]
For what is worth, I also just bought a Pebble for this christmas because I wanted an e-paper display based watch, and having an FOSS sync app on the phone was a must. So the only reason I'm buying it is because this project exists. Thanks for everything devs!

**Comment by danielegobbetti** [comment]
Thank you all very much for the kind words! I'm reluctantly closing this as it was nice to see it in the issue list, anyway keep your positive thoughts headed our way, they are much appreciated :-)
