### ISSUE TITLE
Mi Band 2: Heart Rate measure removes non-synced activity data

### ISSUE THREAD

**Issue by Jojonintendo** [Freeyourgadget/Gadgetbridge#478]
Hello everyone!

Today I noticed something with my Mi Band 2. Whenever I sync the activity data, even after a complete night, it works great, it even shows the average heart rate throughout the night. But through the day, if I manually measure heart rate with the band, and then I synchronize with GB, I will find that every activity before the HR measure will be blank. At least every activity that wasn't synced before.

![photo195225557052532978](https://cloud.githubusercontent.com/assets/24507138/21549282/72a3d404-cdf1-11e6-831d-5508ee2fae4c.jpg)

As you can see, the little yellow spikes are one-time manual heart rate measure. The middle one was took after syncing the data, so it got integrated well. But the other two (the last is difficult to see, but it's there), removed all the non-synced data. I don't think it's removed from the band though, because step count is right on the device.

If I can provide you with any more information, please just tell me. Thanks for your work, and have a good day!

**Comment by cpfeiffer** [comment]
Thanks for the report, I'm about to fix this. The reason is that we ask the band for activity data since a specific date/time. Currently we send the date/time of the last sample in the database. But since we now also store manual hr measurements in the database, we only ask for activity data since the last manual hr measurement. (or live activity usage).
