### ISSUE TITLE
Mi Band 2 Feature Request: Goal notification

### ISSUE THREAD

**Issue by Jojonintendo** [Freeyourgadget/Gadgetbridge#485]
Hi everyone!

Here is the btsnoop of another option of the Mi Fit app, which allows the band to vibrate if the daily step goal is achieved. Thanks for your hard work!

[btsnoop_hci_goal_notification.zip](https://github.com/Freeyourgadget/Gadgetbridge/files/679992/btsnoop_hci_goal_notification.zip)

**Comment by Vebryn** [comment]
Interesting, hopelessly your btsnoop is empty.

**Comment by Jojonintendo** [comment]
Hi,

If I remember correctly, I enabled and disabled the option in the Mi Fit app a few times. If the btsnoop is empty I don't really know how to provide the information needed. I would appreciate any instruction on this.

**Comment by cpfeiffer** [comment]
It's not empty. You have to write 0x06 0x06 0x00 0x01 to the 00000003-... characteristic to enable the notification and 0x06 0x06 0x00 0x00 to disable it.

On success, you get 0x10 0x06 0x06 0x00 0x01 as a change notification.

I actually have all of @Jojonintendo's dumps prepared, but I really didn't find the time to add all those options. (Sorry!) So help is appreciated. I can help deciphering the dumps.

**Comment by Jojonintendo** [comment]
@cpfeiffer Don't worry about all those features, they're completely optional and I love how GB works right now. I really appreciate all the effort this team makes, that's how you make such a great app!

**Comment by joserebelo** [comment]
@cpfeiffer I can add this, plus the other requested options, if it is fine with you.

My only question is about how the change notification should be handled. It seems that one is being sent whenever any configuration is written to that characteristic, and they're currently not being handled for any of the options. Should we be using it to guarantee that the option was applied and and revert it otherwise? This might need an issue of its own.

**Comment by cpfeiffer** [comment]
@joserebelo That's a very good question and a long standing open issue in the BLE part of Gadgetbridge. 

Since it really is a separate topic, I opened #715 and added my current thoughts about this. Discussion and suggestions much appreciated :-)

Back to this topic, I'm more than happy if you can add these options to Gadgetbridge!

**Comment by cpfeiffer** [comment]
Closing, thanks to @joserebelo
