### ISSUE TITLE
cant edit programms in app manager

### ISSUE THREAD

**Issue by pblacky** [Freeyourgadget/Gadgetbridge#490]
I changed to Gadgetbridge a view days ago and now i cant access to my apps in app manager.
when i tap and hold on an app there is no menu appearing for editing, deleting or something else.

please help!

**Comment by danielegobbetti** [comment]
Hello. I assume you are using gadgetbridge with a pebble, but please specify your device. Gadgetbridge supports many.

Two things to know:
- if you installed apps before using GB, you have to install them again in order to manage them
- if you tap and hold on the app icon, you will be able to change the app's position
- if you tap and hold on the app name, you will see the menu to configure / uninstall / etc.

**Comment by pblacky** [comment]
i use a pebble steel and an samsung galaxy S7 edge.
right, i installed all programms BEVORE using Gadgetbridge.
how can i reinstall my apps with Gadgetbridge, i did not find any access to software !?

**Comment by IzzySoft** [comment]
@pblacky Look up the apps you want in the Pebble store via your web browser. On the details page, append `dev_settings=true` to the URL (e.g. [`https://apps.getpebble.com/en_US/application/57caac70be5ad0a9cf000167?section=watchfaces&dev_settings=true`](https://apps.getpebble.com/en_US/application/57caac70be5ad0a9cf000167?section=watchfaces&dev_settings=true). Now, at the end of the page, you will see a link labeled "DOWNLOAD PBW". Click that to download the app. Now use a file manager to open the downloaded file; this will open Gadgetbridge's installer.

**Comment by ashimokawa** [comment]
@pblacky 
Exactly

**Comment by IzzySoft** [comment]
Currently that's as it is, yes. Btw: I've just updated the corresponding page in our Wiki: [Pebble Watchfaces](https://github.com/Freeyourgadget/Gadgetbridge/wiki/Pebble-Watchfaces).
