### ISSUE TITLE
Broadcast Gadgetbridge data to sleep as Android app

### ISSUE THREAD

**Issue by bkt** [Freeyourgadget/Gadgetbridge#498]
Hi and thanks for this good app

I want to suggest you the broadcasting option from Gadget bridge data to Sleep as android.  This is a very common app for sleep tracking with million  of users. 

They can use HR and movement data to predict and propose good sleeping  habits.  Integration  to miband and other cheap will be wonderful. 

They have an api to communicate their app to any other app though standard Android intent

http://sleep.urbandroid.org/documentation/developer-api/wearable-integration-api/

With your software  many devices can be supported  by sleep as android in one plug-in.

**Comment by rplevka** [comment]
this is actually why started to use GB :) i hope this will be available soon

**Comment by danielegobbetti** [comment]
Closing as wontfix. The core team has little interest in implementing the API of a closed source application. Personally I can't even see which permissions the app needs/try the app because I don't have play store on my phone.
You (or the sleep as android devs, or anyone) are welcome to implement this feature in a PR and we will review it.
