### ISSUE TITLE
"Unable to install the given file: /foo/bar.pbw"

### ISSUE THREAD

**Issue by debuti** [Freeyourgadget/Gadgetbridge#535]
When i try to install watchapps from gadgetbridge to my pebble i get the error
"Unable to install the given file: /foo/bar.pbw"

Ive tried with 3-4 watchapps and all of them throws the same result.

My device is a Pebble 5015, with HW version ev2_4 and FW version v2.7. Im running Android 6.0.1 build MMB29M and GadgetBridge 0.17.1. Everything else seems to work OK.

Thanks

**Comment by danielegobbetti** [comment]
This smells a lot like a problem in accessing the file, rather than a problem with the pbw.
There are multiple ways to open pwbs, so please let us know how you tried (and try another approach :-) )
- the "fab" button with the + in the app manager inside gadgetbridge
- tapping a pbw file in a file manager
- tapping a pbw file in the "download manager"
- long tapping a pbw file and "sharing" it to gadgetbridge

**Comment by debuti** [comment]
Nope, none of that options works

- The fab button do not exists with my configuration
- The file manager sends the intent to gadgetbridge and the message its shown (instantly)
- The download manager does the same as the file manager
- The sharing method to FW/App installer does the same as the file manager

I ve upgraded to 0.17.3 and all the same. Thanks for the effort

**Comment by ashimokawa** [comment]
@debuti 
You are trying to install a file for Firmware 1.x on firmware 2.x - that is not supported. 
While you can install files for Firmware 2.x on 3.x or 4.x, Firmware 1.x apps are completely incompatible with anything else

**Comment by ashimokawa** [comment]
Next version will at least have a better error message
