### ISSUE TITLE
Heart rate scan is  not  activating after a particular time period

### ISSUE THREAD

**Issue by yash-bhavsar** [Freeyourgadget/Gadgetbridge#537]
The device is Mi Band 2. In this device, by default, the device performs a heart rate scan at regular intervals of 2 minutes. But after connecting the band to GB, the band does not perform the heart rate scan on its own. We need to surf through the band and manually go to the heart rate feature to do the scan. MiFit app supports this feature, there is no such problem. 
Actually, I am configuring the GB application in such a way that it shows Heart rate in a new fragment and also I am making a linechart to display the heart rate of the user for the whole day. But after connecting the band to the application, the band is not doing the heart rate scan on its own therefore the graph is completely broken. Since my application is completely based on GB there is the same problem. How do I solve this issue ??

**Comment by bluuub** [comment]
I don't know if I misunderstand you:

> The device is Mi Band 2. In this device, by default, the device performs a heart rate scan at regular intervals of 2 minutes. But after connecting the band to GB, the band does not perform the heart rate scan on its own.

This is just not true atleast not as a default. The MI Band 2 does something like this while sleeping (there is a switch in the settings: "Use Heartrate Sensor to improve sleep detection"). Again, this feature only works while the band is monitoring your sleep. 
In the normal usage the band won't perfom ANY heart rate measurements by its own. Maybe I misunderstood you and you are talking about the live activity thing (I have no experience with that).

> Since my application is completely based on GB there is the same problem. How do I solve this issue ??

Why are you developing your own app instead of bringing this feature to GB (I guess there would be more people interested)? I guess you're on your own if you decide to fork this project.

**Comment by yash-bhavsar** [comment]
@bluuub  I know about the "Use Heartrate Sensor to improve sleep detection" because I have been working on adding a heart rate module and have tested the whole pulse rate setting thing. Also, I have already found a workaround: a background service that will do the heart rate scan after every 2 minutes.
The band does perform the heart rate measurement on its own without connecting to any app. The live activity thing is completely different.

**Comment by bluuub** [comment]
Sounds like you're getting somewhere. 👍 

The problem is (and I suppose that is why @danielegobbetti closed the issue): you are working on your own app instead of contributing to this one. So opening issues in this project just causes noise. The devs in this project will likely help you if you pushed your code into this app. If you decide to pursue your own project open an issue in that project and get people to help you there.

**Comment by danielegobbetti** [comment]
Or **at the very least** provide a link to the repo of your libre/open source app, which **must** be compatible with gadgetbridge's license as it's being built upon it.
In any case, this is not an issue for this app.

**Comment by nip10** [comment]
I got a Mi Band 2 today and I'm testing different apps. Im currently using GB but I was looking for the feature that is discussed here: continuous heart rate monitor (ie: every 5-10 mins). Some apps have this function, even in background, without any user action. Is this feature not in the plans for GB or am I missing something ?

**Comment by aytunch** [comment]
@yash-bhavsar could you find the cause?
