### ISSUE TITLE
Add support for Squeaky Mail (k9 Fork) for German Mail Provider Posteo.de

### ISSUE THREAD

**Issue by Teyro** [Freeyourgadget/Gadgetbridge#589]
Hi there,

Can someone add support for Squeaky Mail? It is a K9Mail Fork with support for Inline Mail Encyption (k9 does not support that in the near future)..... I think i should be a one liner in the code? I did not get norifications for mails... Some is for telegram (f-droid Version) un QKSMS ;)

I am useing the MiBand 2 with LineageOS on a OnePlus 2 ;)

forgot to add the App Link https://play.google.com/store/apps/details?id=com.imaeses.squeaky

**Comment by danielegobbetti** [comment]
This is the source repo: https://github.com/imaeses/k-9/

>  I think i should be a one liner in the code?

Indeed it is, and is a perfect target if you want to contribute to our codebase. The file that performs the classification of incoming notiications is: https://github.com/Freeyourgadget/Gadgetbridge/blob/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/AppNotificationType.java

I am not sure what you mean with "I did not get notifications for mails" though, the notification *should* appear on your gadget, only as a "generic" notification instead of email.

Also qksms and telegram are already supported (and should be correctly classified). Are you sure you enabled notification access for Gadgetbridge?

**Comment by danielegobbetti** [comment]
Are the provided suggestions enough for you to add support by yourself? We are approaching release and this could be added.
