### ISSUE TITLE
Bluetooth Tracking Beacon Support?

### ISSUE THREAD

**Issue by maxchill** [Freeyourgadget/Gadgetbridge#619]
Feature request / inquiry into support for bluetooth tags / trackers

I was drawn to Gadgetbridge as it was an opensource application for connecting to my bluetooth wearable.  I'm now looking for an application that does a similar task of connecting to blue tooth tracker (find my keys with bluetooth).

My device is
Chipolo Classic
https://chipolo.net/how-it-works

I'm wondering if it's been considered to add this device type to gadget bridge, as there is significant overlap with what is already in place.

**Comment by alcos0** [comment]
Hi! Me and my fiend love this application and we both have Mi Bands 2. I was going to open a new issue to request a feature, but since it's very similar to this one, here we go: can we add a vibration alert to the wearable when you are distancing from your smartphone? I think it'll be very useful to dumbasses like me who are used to forget things in wrong places.
Thanks.

**Comment by danielegobbetti** [comment]
Please check:

https://github.com/Freeyourgadget/Gadgetbridge/wiki/Support-for-a-new-Device

I'm closing this, feel free to reopen once the needed information is available.

**Comment by maxchill** [comment]
Thanks @danielegobbetti for pointing out where to get started.  This seems like a fun project, and look forward to following the steps provided in order to contribute.

**Comment by danielegobbetti** [comment]
Cool! Looking forward to it. 👍
