### ISSUE TITLE
Pebble Time BLE support

### ISSUE THREAD

**Issue by bluuub** [Freeyourgadget/Gadgetbridge#661]
#### Before opening an issue please confirm the following:
- [x ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
I thought about buying a Pebble since the prices dropped pretty rapidly since the announcment of the fitbit takeover. However bluetooth low energy is a requirment for me. I could not find out wether devices that have hardware support for both normal and LE bluetooth work with Gadgetbridge + LE. In this special case I am talking about the Pebble Time. 
I know that LE support was added to support the Pebble 2 since it only provides LE connections. Does the work that was done to support P2 also enable LE support for the Pebble Time? That means: Can I use the Pebble Time + Gadgetbridge in LE mode and expect it to work (nearly) flawlessly?

IMO this should also be added to the wiki, to ensure that further questions in this direction can be solved by reading the "Getting started part".

#### Your wearable device is:
Pebble Time

#### Your android version is:
7.1

#### Your Gadgetbridge version is:
latest and greatest from fdroid

Best regards & thanks!

**Comment by ashimokawa** [comment]
Yes we support that!

1) Pair your Pebble Time (NOT THE LE, if it is paired unpair) and connect at least once with Gadgetbridge.
2) Use the Add button in Gadgetbridge and pair your LE Pebble through Gadgetbridge while having the "Always prefer BLE" option in Pebble settings on.

You will gain battery life at the cost of stability on some phones. Plus a few other things like longer initial connection times.

This feature is a Gadgetbridge exclusive and was not possible with the Pebble app - they know why. Because BLE on Android is generally crappy.

No idea if this is documented in the wiki, if not we should add that (or you can if you are successful)

**Comment by ashimokawa** [comment]
Just out of curiosity: Why is LE a requirement for you?

**Comment by danielegobbetti** [comment]
If you set the option in gadgetbridge to always use ble it will work with basically every pebble model. However YMMV depending on the phone model / ROM you are using.
I'm having mixed results with plain AOSP (and Sony binary blobs) but the reliability of the reconnection and the stability once established varies greatly with every (binary blob) update. Therefore I think it's not gadgetbridge's fault.
Sorry for not being more helpful.

**Comment by ashimokawa** [comment]
With the original Pebble (max firmware 3.12) BLE only works once until BT gets toggled on the pebble.
All other models seem to work without that annoyance.

**Comment by ShapeShifter499** [comment]
I stopped using BLE for my Pebble Time as it disconnects after a seemingly random amount of time and it never reconnects.

**Comment by ashimokawa** [comment]
@bluuub 
Hint: If you care about battery life and screen readability in low light conditions, definitely get the Pebble 2. You won't get the same battery life out of the Pebble Time.

**Comment by ShapeShifter499** [comment]
@ashimokawa The Pebble time 2 as far better battery?   How long would you say it lasts on one charge?

**Comment by ashimokawa** [comment]
@ShapeShifter499

I typically recharge my Pebble 2 (I do not have a Pebble Time 2, they do not exist in quantities) after 8 days, but it reports 10% or 20% then. So I assume that it would last about 10 days with my use pattern. Which is: HR on, Health on, not excessive notifications, BT off for 8 hours over night, one alarm every morning.

Regarding BLE, passive pebble initiated reconnects never work but active re-connection tries should work. That being said, I totally believe you that it does not work. I do not have any experience how the official app handles that...

**Comment by ShapeShifter499** [comment]
@ashimokawa Sorry I typed "Pebble time 2" when I shouldn't have, I did edit it though the moment I saw it lol. 

I see your mentioning having the HR model. I didn't get the Pebble 2 because it didn't have any new features or improvements from the Pebble Time. But if the Pebble 2 HR has equal/better battery life I might consider trying to get one. I like the HR feature but I was worried about it having worse battery due to the HR. My Pebble Time gets about a week in usage before needing a recharge. 

"active re-connection tries should work."  -- Do you mean going into the app and having it reconnect?  That does work but that's annoying to do as BLE drops often enough I might as well not use BLE.

**Comment by ashimokawa** [comment]
@ShapeShifter499

If you get a week with BT Classic on your PT (which is more than I expected) you _might_ also get 10 days with LE, and since the P2 only supports LE you might have the same BLE battery life. And if you have a different use pattern (like moving more and triggering the constant HR measurement more often and longer) it might even be worse. It is really hard to compare battery time between people with totally different behaviour. So I don't want to be responsible if you use money on a P2 and are disappointed. :smile:  

with "active re-connection" I mean automatic active GB initiated re-connects (number of re-connection tries can be configured in GB)

**Comment by bluuub** [comment]
Maybe I should have kept this one open :P sorry about that.
Forgot to ask one more thing: PT & P2 are fully functional without every touching the official Pebble App? I inted to try to run it without ever creating a Pebble account. Just wanted to make this sure before I buy into it :P

**Comment by ashimokawa** [comment]
@bluuub 
You never ever have to touch the official app or make a pebble account.

About being "fully functional", that depends on what you expect. For example since we do not have the internet permission on purpose, watchapps that want to fetch data from the internet do not work.
We do support weather for selected watchfaces by relying on an external app and we have more features in the pipeline, but we are not 100% feature par with the official app. You might have a look at the list of supported features in README.md and maybe browse the wiki a bit to get an idea where we are right now.

Remember that this project started with the mission to offer a free software alternative to closed source apps that give away your data and NOT to save the pebble infrastructure after the fitbit thing (which some redditors seem to think)

**Comment by ShapeShifter499** [comment]
@ashimokawa So I should change Settings > Pebble Settings > Reconnection Attempts  ?     Is there a limit to the number of reconnections I can have Gadgetbridge attempt?   I just put down 1200 there to see if that helps.

**Comment by bluuub** [comment]
Yeah maybe the "fully functional" comment was to inaccurate. I meant, that I would be able to do everything that is listed in this wiki here. Happy that I understood the wiki right regarding this. The things I care about made it into Gadgetbridge and it is great to see it evolving! 

The only reason I even consider getting a Pebble is that it is supported by Gadgetbridge. And I thank you guys for sticking to the No-Internet-Policy. I was here well before the Fitbit-Pebble stuff was announced. But I guess the userbase might grow in a year when they decided to take down those servers. 

I will just reopen this as there is some other discussion going on ;-)

**Comment by ShapeShifter499** [comment]
@ashimokawa   Reconnection doesn't seem to be working well, it's always stuck in "waiting for reconnect"

**Comment by bluuub** [comment]
Maybe another issue for the reconnection problems would be better suited. Therefore I will close this one again.

Just to update the original question: I bought the Pebble 2 looking forward to try it out. Thanks again for the advice!

**Comment by IzzySoft** [comment]
> The only reason I even consider getting a Pebble is that it is supported by Gadgetbridge.

I can't agree more. Would that not have been the case, I hadn't bought my PTS.

> without having to create a Pebble account to initialize or something.

Exactly. I never had the official app (for privacy reasons), and started right away with GB (somewhere around v0.10). Everything works great. Meanwhile, I've accomplished several firmware upgrades, played with a couple of watch faces, enjoy the details of Pebble Health, use it for navigation (with *Locus Maps* and the Pebble addon)… Everything works great, wonderful support, a great team constantly working at the project – much more than I would expect from any commercial app. And what's more: I feel completely safe concerning my privacy in regards of Pebble use.

So, @bluuub – it looks you have the same thoughts I had initially, so I hope I was able to remove the last doubt. I'm pretty sure you will enjoy a Pebble (whichever model) with GB. The only thing I'm not that happy with is the display of the Pebble, which is a bit too small for my eyes – I had played with the thought to get a P2 once that's mature, but unfortunately that company with the ugly gadgets didn't want me to. Nothing to blame GB for :innocent:

**Comment by bluuub** [comment]
Just to give you guys an update:
Got the Pebble 2 and I am very happy. Was worth the upgrade from the Mi Band 2 and pairing and updating it to and via Gadgetbridge worked flawlessly. I am impressed that even configuring the watchfaces is supported by Gadgetbridge. Really great work! Can't wait for the next release to try out the calendar features :-)

Wiki says that firmware upgrades on the P2 might cause problems. I cannot confirm this. Updating the firmware as suggested took less than 2 minutes and worked on the first try. Concerning the BTLE connection I can confirm some (not very many disconnects - I would say less than 10 in 2 full days). Reconnection happend automatically all the time though (sometimes it just takes a moment, so manually initiating the reconnect is faster sometimes).

Thanks again for the advice in this thread!
