### ISSUE TITLE
chart no clear

### ISSUE THREAD

**Issue by albertsal** [Freeyourgadget/Gadgetbridge#683]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your issue is:
Hi, something does not go back to me, every day at 9am and 13am I do about 1000 steps but in the chart are not displayed.
Also every day I take steps at 00 but I sleep for that hour ...
The log is empty

#### Your wearable device is:
zeblaze:zeband

2.44

#### Your android version is:
galaxy s6  V 6.0.1

#### Your Gadgetbridge version is:
0.19.1

![screenshot_20170509-183514](https://cloud.githubusercontent.com/assets/24717350/25862306/e1223fc6-34e7-11e7-9b59-6f45fccdb823.png)

**Comment by jpbarraca** [comment]
I suspect that you do not have the continuous monitoring feature enabled (check the settings). Therefore, there is no Heart Rate or Activity Intensity info to present. 

Sleep monitoring is still working because the band monitors this autonomously. There are gaps between the lines (during the sleep period) because the band only reports a summary message every 10 minutes.

Step counters should be working because there are provided every 10 minutes by the band, or as a summary after the end of the day.

**Comment by albertsal** [comment]
You're right, I read about continuous monitoring, but I thought it was only for the Heart Rate. Now I understand that it is also useful for the steps. thank you

**Comment by jpbarraca** [comment]
It is useful for real time steps. For step counters you will still get relative counters (number of steps during the interval) with a precision of 10 minutes up to the last 24h, and absolute counters with a precision of 24h for the previous days.

If continuous monitoring is enabled you will get absolute day step, heart rate (and intensity), day calorie, day distance, and battery charge counters every time the band detects movement. Just walk or wave your arm and data will be sent.
