### ISSUE TITLE
Mi Band: Power levels don't refresh (or update very infrequently)

### ISSUE THREAD

**Issue by chrisvella** [Freeyourgadget/Gadgetbridge#71]
I am testing out a build based the master branch.
I noticed the power levels of the mi band don't refresh, or are updated very infrequently.
Not a big deal but I thought I would let you know.
Fixed by disconnecting and reconnecting (closing and reopening the app doesn't seem to work).

**Comment by danielegobbetti** [comment]
We should be getting these values through  notifications, bu they're just ignored ATM.

**Comment by danielegobbetti** [comment]
Hi @chrisvella , after a thorough look I have to say that I'm less optimist than I was previously.

It is true that we register a notification for the Battery characteristic but this is something that lives on "our" side (i.e. the device doesn't know anything about it). In order to get the notifications, we have to write something to another endpoint. There are some known values (realtime steps notification, fetch activity data, ...) but battery isn't among them as far as I know.

Nevertheless, please try installing the branch https://github.com/Freeyourgadget/Gadgetbridge/tree/battery_notification and let me know if it works, but I fear it will not.

**Comment by chrisvella** [comment]
I am testing your build now. Drained the battery around 6%, then usb charged the device whilst gadgetbridge is open. It does not appear to be updating. I had a look at the commit request, it doesn't appear its reliant on any period of time/percent increase?

**Comment by danielegobbetti** [comment]
@chrisvella not it isn't. Ideally you should be seeing the battery level rise/go down in the app, or at least in logcat something like:
characteristic changed: 0000ff0c-0000-1000-8000-00805f9b34fb

where the important part is "ff0c" in the first block.

**Comment by chrisvella** [comment]
@danielegobbetti I have now tried draining the band, and monitoring for battery updates. In my limited testing it doesn't appear to be working. I will keep using the new version and notify you if I see any changes.

**Comment by chrisvella** [comment]
@danielegobbetti I been playing around with it more. I noticed once the device reaches 100%, gadgetbridge very quickly updates the power level!

**Comment by danielegobbetti** [comment]
That's interesting to know, thanks! I guess that once it's fully charged it starts pushing updates by itself. This means (probably!) that we're listening to the right message, but we need to find out how to trigger regular updates from the device.

In any case, if you had a logcat that you can share that would be really helpful. Otherwise I'll just recharge my miband :)

Thanks again for testing!
--

**Comment by cpfeiffer** [comment]
I did get a UUID_CHARACTERISTIC_NOTIFICATION (ff03) change notification while charging, at least once.  Whatever that means. I guess that the device's status somehow changed, maybe we should re-fetch device info when we receive that. Currently we do not handle that in any way.

**Comment by cpfeiffer** [comment]
Interesting: when you unplug the Mi from the charger, it does send a UUID_CHARACTERISTIC_BATTERY notification. So your commit does work.

**Comment by cpfeiffer** [comment]
Same happens when you plug it in, btw. I'll cherry-pick your commit, I hope you don't mind :-)

**Comment by danielegobbetti** [comment]
I am now at 9% charge left, and I started seeing notifications on the battery characteristic every minute:
```
06-30 08:29:45.583 D/nodomain.freeyourgadget.gadgetbridge.btle.BtLEQueue( 9475): characteristic changed: 0000ff0c-0000-1000-8000-00805f9b34fb
06-30 08:30:45.545 D/nodomain.freeyourgadget.gadgetbridge.btle.BtLEQueue( 9475): characteristic changed: 0000ff0c-0000-1000-8000-00805f9b34fb
06-30 08:31:45.561 D/nodomain.freeyourgadget.gadgetbridge.btle.BtLEQueue( 9475): characteristic changed: 0000ff0c-0000-1000-8000-00805f9b34fb
06-30 08:32:46.181 D/nodomain.freeyourgadget.gadgetbridge.btle.BtLEQueue( 9475): characteristic changed: 0000ff0c-0000-1000-8000-00805f9b34fb
06-30 08:33:47.187 D/nodomain.freeyourgadget.gadgetbridge.btle.BtLEQueue( 9475): characteristic changed: 0000ff0c-0000-1000-8000-00805f9b34fb
06-30 08:34:46.947 D/nodomain.freeyourgadget.gadgetbridge.btle.BtLEQueue( 9475): characteristic changed: 0000ff0c-0000-1000-8000-00805f9b34fb
```
I started seeing these when the battery level was at 10% but I didn't take note of the frequency. It may be that the frequency gets higher the less battery is left.

**Comment by danielegobbetti** [comment]
I waited until the miband was at 3% battery and the notifications are still one per minute. I am recharging now.
