### ISSUE TITLE
Donation options for legal expenses etc.

### ISSUE THREAD

**Issue by momo42** [Freeyourgadget/Gadgetbridge#714]
This is a non-technical topic but I think here is the right place for the discussion.

While the gadgetbridge repository was unavailable due to the DMCA takedown notice, I regularly reviewed the state of affairs at Github, Reddit, Heise.de and blog.freeyourgadget.org. (I needed some weeks to find blog.freeyourgadget.org)

I did not know how to contact the developers directly, but I am pleased that some people have offered support during this difficult phase, according to this blog post blog.freeyourgadget.org/our-dmca-takedown-a-post-mortem.html.

Since I'm not a programmer I can not contribute any code, but the developers have made me and my wife very happy with their work. Gadgetbridge has been an important tool in our everyday life for about a year.

I saw on Reddit that the request for a donation opportunity has been kindly ignored so far. So I think, now, after the tracker is available again, this topic should be discussed exactly at this place. I understand and appreciate that the core developers don't want to be paid for their work on this open source project. The hours spent could not be paid adequately anyway.

But I would really like to contribute to the project. I do not think that in addition to their great coding work, developers should be forced to spend private money on legal expenses etc.! But someone must pay the lawyers' bills.

So let's start the discussion! How can we help you?

**Comment by jdesbonnet** [comment]
I stumbled across this project just as it was DCMAed and found that frustrating. In the mean time I found a source code tarball and was able to build, modify and achieve what I wanted (download and export raw data from my MiBand2). I'd be happy contribute a small sum. But it would be useful to know what costs were incurred and to whom. Also payment must be possible through a safe channel.

**Comment by danielegobbetti** [comment]
First of all, thanks for the words of support and sorry for the late reply: in these days we explored some possible options so here we go.

Regarding the legal expenses: we (core developers) agreed on splitting the costs for the counter notice among ourselves. 
 
Regarding donations in general, issue 14 is open since a long time and I believe it would be better to continue the discussion there, but to answer your question: how could you help us?

In this phase you could help us brainstorming a way to collect donations that is:
- transparent for donors
- not creating incentives for developers (we are highly motivated by the core values of the project: vendor independence, free and open source code, privacy) and would like to keep the community driven by those values and not economics
- not creating overhead for us (tax or other income declarations, etc.)

If you have direct experience, we would like to hear from you on this more concrete themes:
- do you know of platforms for collecting donations, their strengths and shortcomings? (E.g. liberapay, gratipay, etc.)
- do you know the European legislations (especially in Germany and Italy) about donations and individuals? (Taxes, bureaucracy, etc.)

If you have insights please follow up on issue 14.
