### ISSUE TITLE
How can I answer/use my canned messages to answer to WhatsApp Notifications Pebble Time

### ISSUE THREAD

**Issue by valli1972** [Freeyourgadget/Gadgetbridge#720]
#### Your Gadgetbridge version is: newest 

I use Gadgetbridge for my Pebble Time Steel. In most cases the software runs great, but there ist one thing missing: I can not answer to my WhatsApp notifications. 
I f.e. would like to use the canned messages stored in my Gadgetbridge app or use emojs. 
Is it possible an how can I do?

Thanks a lot!!!

**Comment by ashimokawa** [comment]
You have to enable untested features in setting and use the feature at your own risk since no one of the core team uses WhatsApp (it has not happened to us, but if you mom gets a reply which was meant to your girlfriend, you have been warned, so please test it with caution and report back if it works)

**Comment by bluuub** [comment]
I am currently testing this. Seems to work fine on Pebbel 2 HR, Android 7.1.2, latest GB and latest WhatsApp without gapps.

I still have to test if it works if several messages from more that one person are unanswered. Will report back!

**Comment by bluuub** [comment]
This is working as expected as well! So feature seems to be working as expected. I will try this for a week and see if I find anything unexpected.
