### ISSUE TITLE
Error on Zeband Plus Smartband

### ISSUE THREAD

**Issue by nbrand** [Freeyourgadget/Gadgetbridge#781]
SMS, Numbers ABS Vanessa soprar with doações between each letter.

Zeband Plus Smartband
Android 6
Gadgetbridge 0.20.1

**Comment by nbrand** [comment]
SMS, Numbers and James appear with spaces between each letter.

Zeband Plus Smartband
Android 6
Gadgetbridge 0.20.1

**Comment by vandreicerqueira** [comment]
Hi, everybody!

#630  solved Chinese chars, but came with this issue. That's because it tries to convert every char in the message to Unicode, but they are 4 bytes long, beginning with 0xff and 0xfe. However, by reading saved Bluetooth traffic from manufacturer's app, one can notice these two bytes are only needed in the beginning of the message, not before each char.

I've compiled the sources and changed it a little bit, and my patch worked like a charm.

in file "_service/devices/hplus/HPlusSupport.java_", at the end of "_encodeStringToDevice_" method, there is a loop responsible for writing the message to output buffer:
```
            for (int j = 0; j < cs.length; j++)
                outBytes.add(cs[j]);

```
I've changed it to:

            
```
            final int j0 = (unicode && i != 0) ? 2 : 0; // no idea what happens in Chinese, so make sure "i" will be checked only in Unicode messages
            for (int j = j0; j < cs.length; j++) // bytes 0xff and 0xfe are only included if i == 0 (beginning of message)
                outBytes.add(cs[j]);

```

I hope @jpbarraca may think this is an useful information.



Regards,

Vandrei Cerqueira

**Comment by jpbarraca** [comment]
I cannot test the Zeband Plus, but I will provide a version with your path so that others can test.

**Comment by vandreicerqueira** [comment]
Great!!!

BTW, I own a S908 (GPS embedded), if you guys need any raw data (or even
help from a newbie programmer), I'm over here, as I've already told Mr.
Gobbetti.

Regards,

Vandrei Cerqueira

2017-09-19 15:09 GMT-03:00 João Paulo Barraca <notifications@github.com>:

**Comment by jpbarraca** [comment]
Any news on this? The updated version works?

Regarding GPS, there are quite a few new messages. Can you use this tool (https://github.com/jpbarraca/hplus_log_parser) to find what these messages could be?

**Comment by tjallingran** [comment]
I just installed the APK with the unicode patch and can confirm that it works. Notifications on my Zeblaze Zeband Plus no longer have spaces between each letter.
