### ISSUE TITLE
fetching data from MiBand doesn't work

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [Freeyourgadget/Gadgetbridge#82]
Hi there,
after the latest update from F-Droid I cannot fetch activity Data anymore. The app tells me it is fetching, but then suddenly switches to disconnected state.

I tried then removed the miband pairing, uninstalled and reinstalled gadgetbridge but the problem remains. Additionally I can no longer see the battery level of my MiBand in the app. This used to work before I uninstalled and reinstalled the app.

I noticed that when readding the device via gadgetbridge app, I saw the screen where it tells me to tap the band a few times as soon as it starts vibrating and blinking. But it never did that. Instead the pairing was completed without that. Notifications work fine.

I have attatched a log-file. 

https://mega.co.nz/#!jMw3wIhZ!ngnoAgUMbFC4mxLzJq7rMWEbwblpbBjzZr6YGp2xVwc

Any Idea?

**Comment by 1337sup3rh4x0r** [comment]
Don't ask me why, but after another reboot of my device (I had already done one before to get the logfile created) all seems to be working nice now. Activity Data is fetched quickly and displayed. Also display of battery state works.

One question though: What is the y-axis' unit in the activity log? :) Is that supposed to make any sense as of yet?

**Comment by cpfeiffer** [comment]
Thanks for the logfile, I'll have a look.

The Mi remembers with whom it was paired/bonded. It remembers the mobile's mac address as as well as the personal information as configured in Gadgetbridge. When this information stays the same, you don't need to re-confirm the pairing AFAIK.

Unfortunately there may be many causes of temporary failures:
- Gadgetbridge itself, or how it communicates with the Mi (possibly depending on the Mi firmware)
- the mobiles' Bluetooth stack
- the Mi Band's bluetooth stack

Even while we strive for perfection, some problems may be best solved with a reboot, because they cannot be fixed within Gadgetbridge.

Re the y-axis: so far, this is the raw, unfiltered "intensity" data from the Mi Band, normalized to the range 0-1. The absolute valus are probably irrelevant, they only make sense in a relative way.

There's much more to come, but I had to get the DB upgrade, downgrade and backup mechanism right before doing anything in that direction.

**Comment by cpfeiffer** [comment]
Looking at the I see that the devices initially connected on the bluetooth level, but no communication happened. We tried to pair, but never received a response. And we couldn't list the Mi Bands services or characteristics, so no wonder nothing worked.

A little later (probably after the reboot) the Mi Band actually responded and you could sync.

Looks like your bluetooth stack was dysfunctional in the beginning.
