### ISSUE TITLE
Uncaught TypeError Pebble Time

### ISSUE THREAD

**Issue by icovelev** [Freeyourgadget/Gadgetbridge#856]
Since the last update 0.22. I'm getting this error and the app crashes sometimes.
![Screenshot ](https://i.imgur.com/0IEo6og.png)
[Log file](https://drive.google.com/file/d/0B_d3x-ieB_MBV2dVWFduU1BKYTQ/view?usp=drivesdk)

**Comment by danielegobbetti** [comment]
Which watchface/watchapp are you trying to configure? Is the experimental support for background js enabled?

**Comment by icovelev** [comment]
I'm trying to configure Aspire Watchface. And tried with both on and off background js.

**Comment by danielegobbetti** [comment]
Ok thanks, will try to reproduce here.

**Comment by danielegobbetti** [comment]
Uhm. If [this](https://apps.getpebble.com/en_US/application/5798b1b81482cd673b0000a2) is the aspire watchface you are referring to, then I see two problems:
1. AFAIK all kiezelpay supported watchapps/faces need an active network connection (for license check) and we don't support this
1. The downloaded pbw has an UUID of ``9da83536-66a0-4aa9-ad0b-f58f21c751d2``, but in your logs I find no matching lines

Please consider that after enabling/disabling the background JS execution you have to disconnect and connect again from the Pebble.

**Comment by icovelev** [comment]
That's strange. Before the update to 0.22 I was able to configure this watchface through Gadgetbridge. My watchface is activated a long time ago through pebble app. After I switched to gadgetbridge I just downloaded the pbw from the store and reinstalled it. Worked like a charm (instead of the weather).  Maybe is something dedicated to my watch. 

Another bug that I found is that when background ja is enabled the support watchfaces (healthify, square) doesn't show the weather info property.

**Comment by danielegobbetti** [comment]
I'm sorry but this watchface's javascript looks so broken to me that I can't think of a proper workaround for the issue you are reporting. I can reproduce it but it doesn't really help. Here is what I found utterly wrong:
1. the watchface accesses the localStorage directly (``.city``) instead of using the proper getItem method
1. the watchface does no sanity check and after getting the (null) ``.city`` (that was never set) performs an unchecked ``split`` as if it was an array
1. it does so after checking which weather provider is enabled (again, in the wrong way) and falls back to Weather Underground that would not be configured anyway

It really looks broken to me beyond repair, and on top of this all the watchface tells me continously that the internet connection is broken (kiezelpay license check)... I'm sorry but we cannot fix this.

**Comment by danielegobbetti** [comment]
If you still have issues with square and healtify or other watchfaces, please open a new issue!
