### ISSUE TITLE
Pebble weather problem whith Huawei P8 Lite 2017

### ISSUE THREAD

**Issue by Gabicu** [Freeyourgadget/Gadgetbridge#882]
I'm sorry for my English.
I am following all these steps, of "Pebble System Apps":
"If your device runs a lower firmware version, you won't have that system app available. In this case, just make sure you install the „provider“ from F-Droid as described, and continue with the next step. Weather will still be available to the watchfaces.
Now, you must enable the Gadgetbridge skin in the Weather notification app: start the app, and flip the Gadgetbridge skin switch as shown in the third screenshot. Also make sure that you have the „Enable Notification“ switch enabled. If you don't want weather information in your notification area, flip off the „Default Skin“. Feel free to adjust the other settings; for weather to work with your Pebble and Gadgetbridge you're already done now."

But it does not appear in Gatgetbridge in tle phone: "Weather system" app.

Android: 7.0
Gadgetbridge
Pebble Firmware: v3.12.3
Phone: Huawei P8 Lite 2017

Any solution?
Thank's for all. # #

**Comment by danielegobbetti** [comment]
The "weather system app" is an app *on the watch*, which is only available with firmware 4.0 on the pebble.
Since you have firmware 3, you will not find any "weather system app" *on your watch*, but  weather in the *watchfaces* should work.
Unfortunately nothing is visible in *Gadgetbridge*, but you should be able to see an entry called "Gadgetbridge" in the Weather notification app.

Unfortunately I am unsure where your problem is... can you try explaining again comparing with what I wrote above?
