### ISSUE TITLE
Add support for Facebook Messenger Lite notifications

### ISSUE THREAD

**Issue by michaelneu** [Freeyourgadget/Gadgetbridge#883]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
I'm using [Facebook Messenger Lite](https://play.google.com/store/apps/details?id=com.facebook.mlite) and Gadgetbridge doesn't recognize its notifications yet as there's only support for the full Facebook Messenger right now. I did a quick source search and found this:

https://github.com/Freeyourgadget/Gadgetbridge/blob/8f06e36c00ae2fdd08459b7ab54f921478eefc5e/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/AppNotificationType.java#L77-L88

I guess adding support for Messenger Lite using the same notification style (since it's basically the same) should be a one-liner, but I haven't tried it yet:
 
```java
put("com.facebook.mlite", NotificationType.FACEBOOK_MESSENGER);
```

I can submit a PR for this, but I'll need to fix my Android Studio install first to ensure it'd work. 

#### Your wearable device is:
Mi Band 2
FW: 1.0.1.53
HW: V0.1.3.2

#### Your android version is:
Android 8.0.0

#### Your Gadgetbridge version is:
0.22.2 (F-Droid)

**Comment by danielegobbetti** [comment]
Please do, as nobody in the core team is on Facebook nor has proprietary apps installed.

**Comment by michaelneu** [comment]
Ok, I'll take a look into it on the weekend.

**Comment by LuccoJ** [comment]
Do also [MaterialFBook](https://github.com/ZeeRooo/MaterialFBook) (me.zeeroooo.materialfb) while you are submitting the PR ;-P

By the way... this should probably be a separate issue, but just so I don't forget to mention it, wouldn't it be less unwieldy in the long run to just support notifications *categories* (each with a generally meaningful icon, with semantics like "incoming chat message", "someone posted something", "a calendar event occurred", etc) and let the user assign specific apps to them, instead of hardcoding it all in the source code file linked above, which seems bound to get longer and longer?

**Comment by michaelneu** [comment]
Sorry for taking so long.

I added the mentioned line and it worked (as expected), so I created a PR.
