### ISSUE TITLE
Feature request: "find my phone" with Amazfit Bip

### ISSUE THREAD

**Issue by LuccoJ** [Freeyourgadget/Gadgetbridge#887]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [x] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [x] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

The latest Amazfit Bip firmware (0.0.9.49, only available in the staging version of Mi Fit 3.1.6.1 at this time) includes a "find my phone" feature in the Settings menu.

According to my logs, Gadgetbridge sees it being invoked as "unhandled event 8". I was not able to obtain Bluetooth logs, but hopefully that is enough information to implement it.

**Comment by ashimokawa** [comment]
@LuccoJ 
I know that we get event 8. But that is not enough and it is more complicated than ringing the phone when we receive it.

The Bip expects a reply after sending out event 8, else it will show an error after some seconds. The real problem is that if you stop the find phone feature we won't get an event, so the phone will ring forever.

The correct procedure would be:
- react to event 8 by sending out some (yet unknown) acknoledgement and let the phone ring
- the bip will probably display something else.
- we stop the find phone feature on the bip and this causes another (yet unknown) event
- we stop ringing the phone

**Comment by ashimokawa** [comment]
It seems that we do get an event when stopping the find phone mode but only if we do that before we get an error.

So with the current knowledge it would be possible to just let the phone ring for a maximum of the timeout timespan.

**Comment by LuccoJ** [comment]
I have looked at how one deals with BtSnoop files, so in case they are useful, here are the parsed logs
* [when connected to MiFit](https://paste.ee/p/0X0pm) (where I let it go for a while, at least past the timeout)
* [when connected to Gadgetbridge](https://paste.ee/p/ofghQ) (where I let it go until it gave the error and returned to the home screen)

**Comment by ashimokawa** [comment]
I implemented this feature quick and dirty, strings are not even translatable...

One todo is make the find phone screen stop on the watch when the button on the app side has been pushed. This is a minor problem because it can dismissed manually on the watch afterwards or one can just wait until it timeouts.

**Comment by IzzySoft** [comment]
He wow! @ashimokawa I hope that feature isn't limited to the AmazFit, but also works with other devices (especially my Pebble Time Steel)? Can't wait to see that! Though my phone rarely goes amiss (it has its special pocket on my belt).

**Comment by ashimokawa** [comment]
@IzzySoft 
Currently this is limited to Bip and Cor, because these have the feature in their firmware.

But I want to release a pbw for pebble which has extra features as an addon for the pebble, find your phone will be one of them, and then I want to ship the pbw inside Gadgetbridge so that everyone can install right away. I still use my pebble, Bip, Cor, Arc and all the upcoming Huami devices kill a lot of time though :O

**Comment by IzzySoft** [comment]
That's good news, @ashimokawa – maybe you also pick the relative of "find your phone", which is "lost your phone" (aka "connection gone")? Pebble should vibrate on that occasion, but mine no longer does. So vibrate and a note (like a calendar entry would place it, just in "reddish style" if possible) would be cool here.

**Comment by ashimokawa** [comment]
@IzzySoft 
Vibration on disconnect is configured per watchface (if supported), there is no standard IIRC.
Technically we could register as a background app (bad for users who already use one) and go to foreground as soon as we register a disconnect, but we cannot send a standard notification from our pebble app itself. Pebble chose a weird path which needs to contact the phone and then send a notification back, no direct access from code running on the pebble :/

**Comment by IzzySoft** [comment]
And somehow TrekVolle fails at that, plus Volle gone silent. Besides: how shall a "notification back" work without a connection?

**Comment by dep** [comment]
Quick note to customers as a workaround who might end up here, you can use the [Tools & Amazfit](https://play.google.com/store/apps/details?id=cz.zdenekhorak.amazfittools) app to find your phone. Mine rings when I tap the button twice in a row. Very handy.
