### ISSUE TITLE
"Reconnect automatically" setting not working after I restart my phone

### ISSUE THREAD

**Issue by frizzo99** [Freeyourgadget/Gadgetbridge#891]
I have my Amazfit Bip paried to GadgetBridge and everything works fine until I restart my phone.  Even though I have "Reconnect automatically" setting checked it doesn't reconnect.  I also have "Start automatically" and "Connect to device when bluetooth.." checked as well.

#### Your wearable device is:
Amazfit Bip Firmware v0.0.9.14

#### Your android version is:
8.0.0

#### Your Gadgetbridge version is:
0.22.4

Log here:  
https://pastebin.com/PkjbxiVD

I did disable my bluetooth around 7:30pm, so the log will show that.

**Comment by LuccoJ** [comment]
Automatic reconnection is very unreliable for me as well (Bip 0.0.9.49, i9300, LineageOS 14.1, GB 0.22.4), although since I have only gotten my Bip recently, I am not really able to say whether this was always a problem or arose recently.
I have also not noticed a pattern related to whether or not I've restarted my phone, but now I'll try to pay attention to that.

**Comment by Prinz23** [comment]
Yeah. I have a similar problem, after the BIP gets out of reach of the phone (Bip 0.11.1.4, CM 12.1, GB 0.23.0) and then gets back in reach, Gadgetbridge is many times stuck in Connecting....  

I have then manually disconnect and re-connect in the App. Instead maybe Gadgetbridge should timeout after some time if the Connecting... status doesn't change to Connected.
