### ISSUE TITLE
i am update firmware to version english of amazfit bip and my amazfit bip is death?

### ISSUE THREAD

**Issue by Caxdax** [Freeyourgadget/Gadgetbridge#914]
#### Before opening an issue please confirm the following:
- [x] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [ ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.

#### Your wearable device is: amazfit bip
Update version: 0.0.9.1.14 EN Mauronofrio

*Please specify model and firmware version if possible*

#### Your Gadgetbridge version is: 0.20.2

*New issues about already solved/documented topics could be closed without further comments. Same for too generic or incomplete reports.*

**Comment by danielegobbetti** [comment]
There is no such thing as "version English" of amazfit bip. You should not flash random files downloaded from the internet on your gadgets. That's why we keep a list of whitelisted/supported firmwares and that's why Gadgetbridge displays a **big fat warning** that any other file is unsupported/unchecked.

(You're running a fairly old build of gadgetbridge by the way)

I'm sorry you bricked your device.

**Comment by ashimokawa** [comment]
@Caxdax 
Where did you get "0.0.9.1.14 EN Mauronofrio", official versions with md5 are listed here 
https://github.com/Freeyourgadget/Gadgetbridge/wiki/Amazfit-Bip-Firmware-Update

I guess your firmware was modified for Mifit users, which at that time always reset the language to Chinese, so people patched Chinese strings to English also and distributed that firmwares.

Also your Gadgetbridge version is not only old (it was the first version that enabled experimental firmware flashing support) I highly suspect you got an **unofficial apk that was build from source BEFORE the actual 0.20.2 release and people distributed via forums because they could not wait for an official release**

Please read also:

https://blog.freeyourgadget.org/beware-of-unknown-apks-online.html


That being said I assume you already tried to long press the power button.

**Comment by ashimokawa** [comment]
I guess you came from here:

https://forum.xda-developers.com/smartwatch/amazfit/amazfit-language-firmware-english-t3670195

So it is pretty sure you used an unofficial apk and an unofficially translated firmware. There is no reason to flash an unofficial firmware, since all >=0.0.9.x firmwares include English and even Mifit wont switch back to English.

**Comment by ingochris** [comment]
> So it is pretty sure you used an unofficial apk and an unofficially translated firmware. There is no reason to flash an unofficial firmware, since all >=0.0.9.x firmwares include English and even Mifit wont switch back to English.

It appears this is no longer true for factory chinese-shipped version A1608 Bips in 2019 on firmwares v.1.1.5.xx+ (my own datapoint and another user's on XDA).
