### ISSUE TITLE
Export DB, short file

### ISSUE THREAD

**Issue by mazertwo** [Freeyourgadget/Gadgetbridge#921]
Hello!

If i export DB, i dont get all database, just only 92kb.
Why?

Thank you!

**Comment by IzzySoft** [comment]
Hi Mazer, you probably received no answer due to "insufficient data" (you didn't tell us what device you have, what Android version, which Gadgetbridge version etc). As in the past 2 years (since you've filed this issue) there were a lot of new releases, including work being done on the DB export code, I'm optimistically assuming your problem is already solved – and thus I'll close this issue. Should I have been wrong, please fill in the gaps mentioned and we reopen.
