### ISSUE TITLE
Pebble: Improve app manager on FW 3.x

### ISSUE THREAD

**Issue by ashimokawa** [Freeyourgadget/Gadgetbridge#93]
It seems that on FW 3.x there is no way to get a list of installed watchapps from the Pebble. Instead the official Pebble App or "the cloud" is responsible for what has to be on your watch and what not. It seems It does so by removing metadata on your watch completely and then reinstalling metadata for apps known to the official Pebble App.

To show at least *something* in the AppManager we preset a list of apps  that where installed in the past by Gadgetbridge (the pbw-cache). With long press it is possible to remove the metadata, and with tapping the app will be started. Removing metadata will keep the app in the list though.

The TODO should be something like:
* ~~resolve app names from the pbw~~
* remove apps from the pbw cache that were deleted from the watch or mark them as removed and allow re-installation of metadata via long press.

If we do not make Gadgetbridge the master of what should be on your Pebble, we provoke inconsistencies. If we do, people switching between both the official App and Gadgetbridge will be surprised with data loss.

**Comment by IzzySoft** [comment]
As per #309 item 2:

> Make it visible whether an app/watchface listed in GB is also installed on the device.

That's a bit tricky with FW 3.x. Details are in the initial post at the referenced issue; just mention it here for context (so it doesn't get forgotten :)

**Comment by tecufanujacu** [comment]
Could be possible add to support to rearrange the watchapp in the Gadgetbridge menu and have the same order on the watch?

**Comment by danielegobbetti** [comment]
Reordering apps is doable. The problem is finding a good approach for the GUI (there are apps in the cache that aren't on the watch, and vice-versa). Do you have something in mind GUI-wise?

**Comment by IzzySoft** [comment]
@danielegobbetti Drag-and-drop is often used in similar context, sometimes even with a "ribbon" attached to each single item where to grab it on. Up-and-down arrows are another approach, but might look a bit old-fashioned :)

**Comment by danielegobbetti** [comment]
Yes, drag and drop is the natural choice here, I agree. However the problem is how to deal with not-installed watchapps. They'll add visual and cognitive overhead, in my opinion.
I was thinking of another way to approach the issue, like a "move to top" context menu entry: this way the user would operate on a single app at a time. Further, I believe this is the most desired functionality.
It's not an ideal solution, though, and I understand that, hence I am not enthusiastic about it.

**Comment by IzzySoft** [comment]
@danielegobbetti

> how to deal with not-installed watchapps

just brainstorming: thinking of the Android *Settings › Apps,* why not adding a second "tab" with "uninstalled apps" if there are any such – similar to the "disabled apps" tab some implementaions have?

> this way the user would operate on a single app at a time

That would be the case with the drag-and-drop approach anyway: you tap-and-hold one app at its "ribbon", and move it to the position where you like to have it.

**Comment by danielegobbetti** [comment]
>just brainstorming: thinking of the Android *Settings › Apps,* why not
>adding a second "tab" with "uninstalled apps" if there are any such –
>similar to the "disabled apps" tab some implementaions have?

Because we don't know which app are on the watch, if the user isn't using only GB.

>That would be the case with the drag-and-drop approach anyway: you
>tap-and-hold one app at its "ribbon", and move it to the position where
>you like to have it.

No, it's not the same. With move to top you act on one app and move it to top, full stop. With drag and drop you act on one app and move it between two other apps, any of the three apps may not be on the watch...

**Comment by IzzySoft** [comment]
Oy – OK, now I got it. Forgot there are folks using both apps. That's an issue indeed – no ideas on that, sorry.

**Comment by tecufanujacu** [comment]
@danielegobbetti 
I don't use the official Pebble App from a lot of time but if I remember correctly from fw 3.x GadgetBridge can't list the the watchapps\watchfaces installed via the official app. Am I in error? GadgetBridge can't know what has been installed without it but there isn't any problem for what we install via GadgetBridge, right?
So I think that could be at least useful reorder what we install via GadgetBridge and could be also useful have a tab for the things installed on the watch and a separate tab for what we uninstalled from the watch but we can leave in  GadgetBridge to reinstall in future, as suggest by @IzzySoft. 

If we are not more able to check what has been installed via the official app I think that we should at least be able to correctly manage what we do via GadgetBridge, also because I think that who switch to GadgetBridge will not use more the official app.

We should only warn about this and who switch from Pebble app to GadgetBridge has to reinstall its app otherwise will not be able to manage them.

**Comment by ashimokawa** [comment]
In current master, there is a new AppManager, which keeps track of installed apps on a per-device basis.
It also allows sorting apps.

The official app will wipe everything clean, and we cannot track that.

**Comment by tecufanujacu** [comment]
I have some question, how can we see how much free space we have in our watches? I know that there is a limit of how many apps we can install in our watches, when we reach this limit what GadgetBridge does?
Is possible to add in the AppManager a voice that indicates the total space of our watches, the used space and the free space?

**Comment by ashimokawa** [comment]
@tecufanujacu 
We cannot ask the watch for free space unfortunately. That is not supported by the firmware.

What happens if flash is full -  good question. I have not managed to fill it up yet.

But unconfirmed rumors go like this:
The pebble flushes out unused apps and leaves the metadata installed on the watch (ie. it will still show up on the watch). Then it would send an "app fetch" request if the app gets started again which would make Gadgetbridge to reinstall the app.

Let us know if you experienced anything like that.

Oh, and I will close this issue since at least its scope seems to be done.
