### ISSUE TITLE
AmazFit Bip : MiFit "Watch display settings" get "corrupted" when updating Watch faces through GB

### ISSUE THREAD

**Issue by clemens68** [Freeyourgadget/Gadgetbridge#957]
#### Before opening an issue please confirm the following:
- [X ] I have read the [wiki](https://github.com/Freeyourgadget/Gadgetbridge/wiki), and I didn't find a solution to my problem / an answer to my question.
- [X ] I have searched the [issues](https://github.com/Freeyourgadget/Gadgetbridge/issues), and I didn't find a solution to my problem / an answer to my question.
- [X ] If you upload an image or other content, please make sure you have read and understood the [github policies and terms of services](https://help.github.com/articles/github-terms-of-service/#1-responsibility-for-user-generated-content)

#### Your issue is:
*MiFit allows choosing items to be displayed on the watch (menu "Watch display settings"). When you remove one or more of the (initially) available items and then update watchfaces through GB there are still the same amount of items as configured through MiFit BUT the items are not the ones selected in MiFit the n items in the original order.
That said: setting "Watch display settings" would be a nice feature for Amazfit Bip*

#### Your wearable device is:
Amazfit Bip

*Please specify model and firmware version if possible*
Bip, Fw: 0.1.0.51

#### Your android version is:
Oreo, PixelExperience

#### Your Gadgetbridge version is:
0.24.1

**Comment by ashimokawa** [comment]
Having never used misfit I have to ask:

Is this a feature to disable items on the watchfaces? Or on the watch menu?

**Comment by clemens68** [comment]
**The "watch menu"**. 
E.g.: I don't need "Compass", Weather and "Timer" and removed them. So I just got "Activities", "Status", "Alarm" and "Settings"

**Comment by ashimokawa** [comment]
@clemens68 

Hmm, the issue title says watch face. I think now I get it, you are not a Gadgetbridge user but only use Gadgetbridge for flashing watchfaces?

I know that FW 0.1.0.51 suddenly honors the settings we sent upon each connect and which were originally meant for Mi Band 2. That is why I removed that feature in Gadgetbridge 0.24.1 - after seeing stuff vanishing from my Bip on firmware 0.1.0.51.

So now, no changes are sent to the Bip upon connect any more. I am confused because you report that error for Gadgetbridge 0.24.1 which should not touch the settings anymore... <=0.24.0 did "corrupt" settings  for newer Bip beta firmwares though.

I hesitate a bit to implement this feature properly because it was the last thing I did before my Bip bricked completely. It has a bootloop forever.  What I did is trying to enable the 9th menu item (I saw a big Alipay logo when unpacking resources and assumed it was a 9th item after settings which I tried to enable).

**Comment by clemens68** [comment]
>I think now I get it, you are not a Gadgetbridge user but only use Gadgetbridge for flashing watchfaces?
I (still) use both MiFit and GB

>Gadgetbridge 0.24.1 which should not touch the settings anymore
you are right! **This issue is fixed in 0.24.1**. Sorry me!

I must have been on 0.24.0 (and before) when noticing this.

**Comment by cpfeiffer** [comment]
Thanks closing.
