### ISSUE TITLE
Amazfit BIP and problem with weather and backlighting the watch at wrist movement

### ISSUE THREAD

**Issue by tomurbanowicz** [Freeyourgadget/Gadgetbridge#986]
In Amazfit BIP it is problem with weather - do not working after choosing a location.
And how to turn off backlighting the watch at wrist movement? Please add this option.

**Comment by danielegobbetti** [comment]
Please use the issue template. For weather issues especially we **need** to know which ROM you are using.

The option to not turn on backlight is already present in the settings (miband / bip section)

**Comment by tomurbanowicz** [comment]
I use Samsung Galaxy S7 and ROM - SuperMan ROM (custom) but base is stock.


Pozdrawiam,
---
Tomasz Urbanowicz
http://www.urbanowicz.net.pl
http://blog.urbanowicz.net.pl
http://www.facebook.com/foto.urbanowicz
tel. 733 222 733

2018-02-09 21:10 GMT+01:00 Daniele Gobbetti <notifications@github.com>:

**Comment by danielegobbetti** [comment]
Closing, as all relevant information were provided

**Comment by ktau221** [comment]
When use Amazfit bip (v.1.1.2.05) and Mi app (3.4.8) + Gadgetbridge (0.29.1)
1) use Mi app and **enable** "turn on screen back light when lift wrist",
2) turn on screen back light when lift wrist, it's work.
3) use Gadgetbridge and **connected** to Amazfit bip
4) turn on screen light back light when lift wrist, then it's not work.
5) use Mi app and **disable** "turn on screen back light when lift wrist",
6) use Mi app and **enable** "turn on screen back light when lift wrist",
7) turn on screen back light when lift wrist, it's work again.


I think Mi app , only send once setting to Bip, because i try to uninstall and install Mi app , this setting look like run 5), 6) again.

**Comment by cpfeiffer** [comment]
You can configure this in Gadgetbridge, see @ashimokawa's comment above.

**Comment by ktau221** [comment]
Amazing! Thanks
